// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bpm/v1/bpm.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Definition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcessKey    string                 `protobuf:"bytes,2,opt,name=process_key,json=processKey,proto3" json:"process_key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Module        string                 `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{0}
}

func (x *Definition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Definition) GetProcessKey() string {
	if x != nil {
		return x.ProcessKey
	}
	return ""
}

func (x *Definition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Definition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Definition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Definition) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Definition) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Definition) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Definition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Definition) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDefinitionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Module          string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Keyword         string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	IncludeInactive bool                   `protobuf:"varint,3,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	PageSize        int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListDefinitionsRequest) Reset() {
	*x = ListDefinitionsRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsRequest) ProtoMessage() {}

func (x *ListDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{1}
}

func (x *ListDefinitionsRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ListDefinitionsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListDefinitionsRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

func (x *ListDefinitionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDefinitionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListDefinitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definitions   []*Definition          `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefinitionsResponse) Reset() {
	*x = ListDefinitionsResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsResponse) ProtoMessage() {}

func (x *ListDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{2}
}

func (x *ListDefinitionsResponse) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *ListDefinitionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionRequest) Reset() {
	*x = GetDefinitionRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionRequest) ProtoMessage() {}

func (x *GetDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{3}
}

func (x *GetDefinitionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDefinitionDiagramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionDiagramRequest) Reset() {
	*x = GetDefinitionDiagramRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionDiagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionDiagramRequest) ProtoMessage() {}

func (x *GetDefinitionDiagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionDiagramRequest.ProtoReflect.Descriptor instead.
func (*GetDefinitionDiagramRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{4}
}

func (x *GetDefinitionDiagramRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DefinitionDiagram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BpmnXml       string                 `protobuf:"bytes,2,opt,name=bpmn_xml,json=bpmnXml,proto3" json:"bpmn_xml,omitempty"`
	ProcessKey    string                 `protobuf:"bytes,3,opt,name=process_key,json=processKey,proto3" json:"process_key,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefinitionDiagram) Reset() {
	*x = DefinitionDiagram{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefinitionDiagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefinitionDiagram) ProtoMessage() {}

func (x *DefinitionDiagram) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefinitionDiagram.ProtoReflect.Descriptor instead.
func (*DefinitionDiagram) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{5}
}

func (x *DefinitionDiagram) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DefinitionDiagram) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *DefinitionDiagram) GetProcessKey() string {
	if x != nil {
		return x.ProcessKey
	}
	return ""
}

func (x *DefinitionDiagram) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeployDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BpmnXml       string                 `protobuf:"bytes,1,opt,name=bpmn_xml,json=bpmnXml,proto3" json:"bpmn_xml,omitempty"`
	ProcessKey    string                 `protobuf:"bytes,2,opt,name=process_key,json=processKey,proto3" json:"process_key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Module        string                 `protobuf:"bytes,6,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployDefinitionRequest) Reset() {
	*x = DeployDefinitionRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDefinitionRequest) ProtoMessage() {}

func (x *DeployDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeployDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{6}
}

func (x *DeployDefinitionRequest) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *DeployDefinitionRequest) GetProcessKey() string {
	if x != nil {
		return x.ProcessKey
	}
	return ""
}

func (x *DeployDefinitionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployDefinitionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeployDefinitionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DeployDefinitionRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type InstanceSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ZeebeInstanceKey    int64                  `protobuf:"varint,2,opt,name=zeebe_instance_key,json=zeebeInstanceKey,proto3" json:"zeebe_instance_key,omitempty"`
	ProcessDefinitionId string                 `protobuf:"bytes,3,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	ProcessName         string                 `protobuf:"bytes,4,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Status              string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep         string                 `protobuf:"bytes,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	AssignedAgent       string                 `protobuf:"bytes,7,opt,name=assigned_agent,json=assignedAgent,proto3" json:"assigned_agent,omitempty"`
	SlaStatus           string                 `protobuf:"bytes,8,opt,name=sla_status,json=slaStatus,proto3" json:"sla_status,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstanceSummary) Reset() {
	*x = InstanceSummary{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceSummary) ProtoMessage() {}

func (x *InstanceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceSummary.ProtoReflect.Descriptor instead.
func (*InstanceSummary) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{7}
}

func (x *InstanceSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceSummary) GetZeebeInstanceKey() int64 {
	if x != nil {
		return x.ZeebeInstanceKey
	}
	return 0
}

func (x *InstanceSummary) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

func (x *InstanceSummary) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *InstanceSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceSummary) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *InstanceSummary) GetAssignedAgent() string {
	if x != nil {
		return x.AssignedAgent
	}
	return ""
}

func (x *InstanceSummary) GetSlaStatus() string {
	if x != nil {
		return x.SlaStatus
	}
	return ""
}

func (x *InstanceSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InstanceSummary) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type InstanceDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ZeebeInstanceKey    int64                  `protobuf:"varint,2,opt,name=zeebe_instance_key,json=zeebeInstanceKey,proto3" json:"zeebe_instance_key,omitempty"`
	ProcessDefinitionId string                 `protobuf:"bytes,3,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	ProcessName         string                 `protobuf:"bytes,4,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	Status              string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStep         string                 `protobuf:"bytes,6,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	Variables           *structpb.Struct       `protobuf:"bytes,7,opt,name=variables,proto3" json:"variables,omitempty"`
	AssignedAgent       string                 `protobuf:"bytes,8,opt,name=assigned_agent,json=assignedAgent,proto3" json:"assigned_agent,omitempty"`
	SlaStatus           string                 `protobuf:"bytes,9,opt,name=sla_status,json=slaStatus,proto3" json:"sla_status,omitempty"`
	BpmnXml             string                 `protobuf:"bytes,10,opt,name=bpmn_xml,json=bpmnXml,proto3" json:"bpmn_xml,omitempty"`
	ActiveElementIds    []string               `protobuf:"bytes,11,rep,name=active_element_ids,json=activeElementIds,proto3" json:"active_element_ids,omitempty"`
	CompletedElementIds []string               `protobuf:"bytes,12,rep,name=completed_element_ids,json=completedElementIds,proto3" json:"completed_element_ids,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstanceDetail) Reset() {
	*x = InstanceDetail{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceDetail) ProtoMessage() {}

func (x *InstanceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceDetail.ProtoReflect.Descriptor instead.
func (*InstanceDetail) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{8}
}

func (x *InstanceDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceDetail) GetZeebeInstanceKey() int64 {
	if x != nil {
		return x.ZeebeInstanceKey
	}
	return 0
}

func (x *InstanceDetail) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

func (x *InstanceDetail) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *InstanceDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceDetail) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *InstanceDetail) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *InstanceDetail) GetAssignedAgent() string {
	if x != nil {
		return x.AssignedAgent
	}
	return ""
}

func (x *InstanceDetail) GetSlaStatus() string {
	if x != nil {
		return x.SlaStatus
	}
	return ""
}

func (x *InstanceDetail) GetBpmnXml() string {
	if x != nil {
		return x.BpmnXml
	}
	return ""
}

func (x *InstanceDetail) GetActiveElementIds() []string {
	if x != nil {
		return x.ActiveElementIds
	}
	return nil
}

func (x *InstanceDetail) GetCompletedElementIds() []string {
	if x != nil {
		return x.CompletedElementIds
	}
	return nil
}

func (x *InstanceDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InstanceDetail) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ListInstancesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProcessDefinitionId string                 `protobuf:"bytes,1,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	Status              string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Module              string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	Keyword             string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	FromDate            string                 `protobuf:"bytes,5,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate              string                 `protobuf:"bytes,6,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	PageSize            int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken           string                 `protobuf:"bytes,8,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{9}
}

func (x *ListInstancesRequest) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

func (x *ListInstancesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInstancesRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ListInstancesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListInstancesRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *ListInstancesRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

func (x *ListInstancesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInstancesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*InstanceSummary     `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{10}
}

func (x *ListInstancesResponse) GetInstances() []*InstanceSummary {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListInstancesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{11}
}

func (x *GetInstanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInstanceEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceEventsRequest) Reset() {
	*x = GetInstanceEventsRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceEventsRequest) ProtoMessage() {}

func (x *GetInstanceEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceEventsRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceEventsRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{12}
}

func (x *GetInstanceEventsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInstanceEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetInstanceEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ProcessEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcessInstanceId string                 `protobuf:"bytes,2,opt,name=process_instance_id,json=processInstanceId,proto3" json:"process_instance_id,omitempty"`
	EventType         string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Source            string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Data              *structpb.Struct       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProcessEvent) Reset() {
	*x = ProcessEvent{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessEvent) ProtoMessage() {}

func (x *ProcessEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessEvent.ProtoReflect.Descriptor instead.
func (*ProcessEvent) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessEvent) GetProcessInstanceId() string {
	if x != nil {
		return x.ProcessInstanceId
	}
	return ""
}

func (x *ProcessEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ProcessEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProcessEvent) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetInstanceEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ProcessEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceEventsResponse) Reset() {
	*x = GetInstanceEventsResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceEventsResponse) ProtoMessage() {}

func (x *GetInstanceEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceEventsResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceEventsResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{14}
}

func (x *GetInstanceEventsResponse) GetEvents() []*ProcessEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetInstanceEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetHeatmapRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProcessDefinitionId string                 `protobuf:"bytes,1,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetHeatmapRequest) Reset() {
	*x = GetHeatmapRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeatmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeatmapRequest) ProtoMessage() {}

func (x *GetHeatmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeatmapRequest.ProtoReflect.Descriptor instead.
func (*GetHeatmapRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{15}
}

func (x *GetHeatmapRequest) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

type HeatmapStep struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ElementId          string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	ElementName        string                 `protobuf:"bytes,2,opt,name=element_name,json=elementName,proto3" json:"element_name,omitempty"`
	InstanceCount      int32                  `protobuf:"varint,3,opt,name=instance_count,json=instanceCount,proto3" json:"instance_count,omitempty"`
	AvgDurationSeconds float64                `protobuf:"fixed64,4,opt,name=avg_duration_seconds,json=avgDurationSeconds,proto3" json:"avg_duration_seconds,omitempty"`
	Severity           string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeatmapStep) Reset() {
	*x = HeatmapStep{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatmapStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatmapStep) ProtoMessage() {}

func (x *HeatmapStep) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatmapStep.ProtoReflect.Descriptor instead.
func (*HeatmapStep) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{16}
}

func (x *HeatmapStep) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *HeatmapStep) GetElementName() string {
	if x != nil {
		return x.ElementName
	}
	return ""
}

func (x *HeatmapStep) GetInstanceCount() int32 {
	if x != nil {
		return x.InstanceCount
	}
	return 0
}

func (x *HeatmapStep) GetAvgDurationSeconds() float64 {
	if x != nil {
		return x.AvgDurationSeconds
	}
	return 0
}

func (x *HeatmapStep) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type GetHeatmapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*HeatmapStep         `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeatmapResponse) Reset() {
	*x = GetHeatmapResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeatmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeatmapResponse) ProtoMessage() {}

func (x *GetHeatmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeatmapResponse.ProtoReflect.Descriptor instead.
func (*GetHeatmapResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{17}
}

func (x *GetHeatmapResponse) GetSteps() []*HeatmapStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type TemplateVariable struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VariableName   string                 `protobuf:"bytes,2,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	SourceType     string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceField    string                 `protobuf:"bytes,4,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`
	ResolverConfig *structpb.Struct       `protobuf:"bytes,5,opt,name=resolver_config,json=resolverConfig,proto3" json:"resolver_config,omitempty"`
	FallbackValue  string                 `protobuf:"bytes,6,opt,name=fallback_value,json=fallbackValue,proto3" json:"fallback_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TemplateVariable) Reset() {
	*x = TemplateVariable{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateVariable) ProtoMessage() {}

func (x *TemplateVariable) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateVariable.ProtoReflect.Descriptor instead.
func (*TemplateVariable) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{18}
}

func (x *TemplateVariable) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateVariable) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *TemplateVariable) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *TemplateVariable) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

func (x *TemplateVariable) GetResolverConfig() *structpb.Struct {
	if x != nil {
		return x.ResolverConfig
	}
	return nil
}

func (x *TemplateVariable) GetFallbackValue() string {
	if x != nil {
		return x.FallbackValue
	}
	return ""
}

type Template struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcessDefinitionId string                 `protobuf:"bytes,2,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	Name                string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TemplateText        string                 `protobuf:"bytes,4,opt,name=template_text,json=templateText,proto3" json:"template_text,omitempty"`
	Module              string                 `protobuf:"bytes,5,opt,name=module,proto3" json:"module,omitempty"`
	Variables           []*TemplateVariable    `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Template) Reset() {
	*x = Template{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Template) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Template) ProtoMessage() {}

func (x *Template) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Template.ProtoReflect.Descriptor instead.
func (*Template) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{19}
}

func (x *Template) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Template) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

func (x *Template) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Template) GetTemplateText() string {
	if x != nil {
		return x.TemplateText
	}
	return ""
}

func (x *Template) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Template) GetVariables() []*TemplateVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *Template) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Template) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListTemplatesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProcessDefinitionId string                 `protobuf:"bytes,1,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	Module              string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Keyword             string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	PageSize            int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken           string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{20}
}

func (x *ListTemplatesRequest) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

func (x *ListTemplatesRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ListTemplatesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListTemplatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTemplatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*Template            `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{21}
}

func (x *ListTemplatesResponse) GetTemplates() []*Template {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateTemplateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProcessDefinitionId string                 `protobuf:"bytes,1,opt,name=process_definition_id,json=processDefinitionId,proto3" json:"process_definition_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TemplateText        string                 `protobuf:"bytes,3,opt,name=template_text,json=templateText,proto3" json:"template_text,omitempty"`
	Module              string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Variables           []*TemplateVariable    `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTemplateRequest) GetProcessDefinitionId() string {
	if x != nil {
		return x.ProcessDefinitionId
	}
	return ""
}

func (x *CreateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTemplateRequest) GetTemplateText() string {
	if x != nil {
		return x.TemplateText
	}
	return ""
}

func (x *CreateTemplateRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *CreateTemplateRequest) GetVariables() []*TemplateVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TemplateText  string                 `protobuf:"bytes,3,opt,name=template_text,json=templateText,proto3" json:"template_text,omitempty"`
	Module        string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Variables     []*TemplateVariable    `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTemplateRequest) GetTemplateText() string {
	if x != nil {
		return x.TemplateText
	}
	return ""
}

func (x *UpdateTemplateRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *UpdateTemplateRequest) GetVariables() []*TemplateVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{25}
}

type RenderTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderTemplateRequest) Reset() {
	*x = RenderTemplateRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderTemplateRequest) ProtoMessage() {}

func (x *RenderTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderTemplateRequest.ProtoReflect.Descriptor instead.
func (*RenderTemplateRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{26}
}

func (x *RenderTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenderTemplateRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ResolvedVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariableName  string                 `protobuf:"bytes,1,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	ResolvedValue string                 `protobuf:"bytes,2,opt,name=resolved_value,json=resolvedValue,proto3" json:"resolved_value,omitempty"`
	UsedFallback  bool                   `protobuf:"varint,3,opt,name=used_fallback,json=usedFallback,proto3" json:"used_fallback,omitempty"`
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedVariable) Reset() {
	*x = ResolvedVariable{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedVariable) ProtoMessage() {}

func (x *ResolvedVariable) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedVariable.ProtoReflect.Descriptor instead.
func (*ResolvedVariable) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{27}
}

func (x *ResolvedVariable) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *ResolvedVariable) GetResolvedValue() string {
	if x != nil {
		return x.ResolvedValue
	}
	return ""
}

func (x *ResolvedVariable) GetUsedFallback() bool {
	if x != nil {
		return x.UsedFallback
	}
	return false
}

func (x *ResolvedVariable) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

type RenderTemplateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RenderedText      string                 `protobuf:"bytes,1,opt,name=rendered_text,json=renderedText,proto3" json:"rendered_text,omitempty"`
	ResolvedVariables []*ResolvedVariable    `protobuf:"bytes,2,rep,name=resolved_variables,json=resolvedVariables,proto3" json:"resolved_variables,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RenderTemplateResponse) Reset() {
	*x = RenderTemplateResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderTemplateResponse) ProtoMessage() {}

func (x *RenderTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderTemplateResponse.ProtoReflect.Descriptor instead.
func (*RenderTemplateResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{28}
}

func (x *RenderTemplateResponse) GetRenderedText() string {
	if x != nil {
		return x.RenderedText
	}
	return ""
}

func (x *RenderTemplateResponse) GetResolvedVariables() []*ResolvedVariable {
	if x != nil {
		return x.ResolvedVariables
	}
	return nil
}

type ListVariableSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVariableSourcesRequest) Reset() {
	*x = ListVariableSourcesRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVariableSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariableSourcesRequest) ProtoMessage() {}

func (x *ListVariableSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariableSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListVariableSourcesRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{29}
}

type VariableSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableSource) Reset() {
	*x = VariableSource{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableSource) ProtoMessage() {}

func (x *VariableSource) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableSource.ProtoReflect.Descriptor instead.
func (*VariableSource) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{30}
}

func (x *VariableSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VariableSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariableSource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListVariableSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*VariableSource      `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVariableSourcesResponse) Reset() {
	*x = ListVariableSourcesResponse{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVariableSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVariableSourcesResponse) ProtoMessage() {}

func (x *ListVariableSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVariableSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListVariableSourcesResponse) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{31}
}

func (x *ListVariableSourcesResponse) GetSources() []*VariableSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ConfigureVariableMappingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TemplateId     string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	VariableName   string                 `protobuf:"bytes,2,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	SourceType     string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceField    string                 `protobuf:"bytes,4,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`
	ResolverConfig *structpb.Struct       `protobuf:"bytes,5,opt,name=resolver_config,json=resolverConfig,proto3" json:"resolver_config,omitempty"`
	FallbackValue  string                 `protobuf:"bytes,6,opt,name=fallback_value,json=fallbackValue,proto3" json:"fallback_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureVariableMappingRequest) Reset() {
	*x = ConfigureVariableMappingRequest{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureVariableMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureVariableMappingRequest) ProtoMessage() {}

func (x *ConfigureVariableMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureVariableMappingRequest.ProtoReflect.Descriptor instead.
func (*ConfigureVariableMappingRequest) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{32}
}

func (x *ConfigureVariableMappingRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ConfigureVariableMappingRequest) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *ConfigureVariableMappingRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ConfigureVariableMappingRequest) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

func (x *ConfigureVariableMappingRequest) GetResolverConfig() *structpb.Struct {
	if x != nil {
		return x.ResolverConfig
	}
	return nil
}

func (x *ConfigureVariableMappingRequest) GetFallbackValue() string {
	if x != nil {
		return x.FallbackValue
	}
	return ""
}

type VariableMapping struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId     string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	VariableName   string                 `protobuf:"bytes,3,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	SourceType     string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceField    string                 `protobuf:"bytes,5,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`
	ResolverConfig *structpb.Struct       `protobuf:"bytes,6,opt,name=resolver_config,json=resolverConfig,proto3" json:"resolver_config,omitempty"`
	FallbackValue  string                 `protobuf:"bytes,7,opt,name=fallback_value,json=fallbackValue,proto3" json:"fallback_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VariableMapping) Reset() {
	*x = VariableMapping{}
	mi := &file_bpm_v1_bpm_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableMapping) ProtoMessage() {}

func (x *VariableMapping) ProtoReflect() protoreflect.Message {
	mi := &file_bpm_v1_bpm_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableMapping.ProtoReflect.Descriptor instead.
func (*VariableMapping) Descriptor() ([]byte, []int) {
	return file_bpm_v1_bpm_proto_rawDescGZIP(), []int{33}
}

func (x *VariableMapping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VariableMapping) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *VariableMapping) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *VariableMapping) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *VariableMapping) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

func (x *VariableMapping) GetResolverConfig() *structpb.Struct {
	if x != nil {
		return x.ResolverConfig
	}
	return nil
}

func (x *VariableMapping) GetFallbackValue() string {
	if x != nil {
		return x.FallbackValue
	}
	return ""
}

var File_bpm_v1_bpm_proto protoreflect.FileDescriptor

const file_bpm_v1_bpm_proto_rawDesc = "" +
	"\n" +
	"\x10bpm/v1/bpm.proto\x12\x06bpm.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xd4\x02\n" +
	"\n" +
	"Definition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprocess_key\x18\x02 \x01(\tR\n" +
	"processKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06module\x18\x06 \x01(\tR\x06module\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb1\x01\n" +
	"\x16ListDefinitionsRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12)\n" +
	"\x10include_inactive\x18\x03 \x01(\bR\x0fincludeInactive\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"w\n" +
	"\x17ListDefinitionsResponse\x124\n" +
	"\vdefinitions\x18\x01 \x03(\v2\x12.bpm.v1.DefinitionR\vdefinitions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"&\n" +
	"\x14GetDefinitionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x1bGetDefinitionDiagramRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x11DefinitionDiagram\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bbpmn_xml\x18\x02 \x01(\tR\abpmnXml\x12\x1f\n" +
	"\vprocess_key\x18\x03 \x01(\tR\n" +
	"processKey\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"\xbf\x01\n" +
	"\x17DeployDefinitionRequest\x12\x19\n" +
	"\bbpmn_xml\x18\x01 \x01(\tR\abpmnXml\x12\x1f\n" +
	"\vprocess_key\x18\x02 \x01(\tR\n" +
	"processKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06module\x18\x06 \x01(\tR\x06module\"\xa1\x03\n" +
	"\x0fInstanceSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12zeebe_instance_key\x18\x02 \x01(\x03R\x10zeebeInstanceKey\x122\n" +
	"\x15process_definition_id\x18\x03 \x01(\tR\x13processDefinitionId\x12!\n" +
	"\fprocess_name\x18\x04 \x01(\tR\vprocessName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x06 \x01(\tR\vcurrentStep\x12%\n" +
	"\x0eassigned_agent\x18\a \x01(\tR\rassignedAgent\x12\x1d\n" +
	"\n" +
	"sla_status\x18\b \x01(\tR\tslaStatus\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xd4\x04\n" +
	"\x0eInstanceDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12zeebe_instance_key\x18\x02 \x01(\x03R\x10zeebeInstanceKey\x122\n" +
	"\x15process_definition_id\x18\x03 \x01(\tR\x13processDefinitionId\x12!\n" +
	"\fprocess_name\x18\x04 \x01(\tR\vprocessName\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fcurrent_step\x18\x06 \x01(\tR\vcurrentStep\x125\n" +
	"\tvariables\x18\a \x01(\v2\x17.google.protobuf.StructR\tvariables\x12%\n" +
	"\x0eassigned_agent\x18\b \x01(\tR\rassignedAgent\x12\x1d\n" +
	"\n" +
	"sla_status\x18\t \x01(\tR\tslaStatus\x12\x19\n" +
	"\bbpmn_xml\x18\n" +
	" \x01(\tR\abpmnXml\x12,\n" +
	"\x12active_element_ids\x18\v \x03(\tR\x10activeElementIds\x122\n" +
	"\x15completed_element_ids\x18\f \x03(\tR\x13completedElementIds\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\x86\x02\n" +
	"\x14ListInstancesRequest\x122\n" +
	"\x15process_definition_id\x18\x01 \x01(\tR\x13processDefinitionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x1b\n" +
	"\tfrom_date\x18\x05 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x06 \x01(\tR\x06toDate\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\b \x01(\tR\tpageToken\"v\n" +
	"\x15ListInstancesResponse\x125\n" +
	"\tinstances\x18\x01 \x03(\v2\x17.bpm.v1.InstanceSummaryR\tinstances\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"$\n" +
	"\x12GetInstanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"f\n" +
	"\x18GetInstanceEventsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xec\x01\n" +
	"\fProcessEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x13process_instance_id\x18\x02 \x01(\tR\x11processInstanceId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"q\n" +
	"\x19GetInstanceEventsResponse\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.bpm.v1.ProcessEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"G\n" +
	"\x11GetHeatmapRequest\x122\n" +
	"\x15process_definition_id\x18\x01 \x01(\tR\x13processDefinitionId\"\xc4\x01\n" +
	"\vHeatmapStep\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12!\n" +
	"\felement_name\x18\x02 \x01(\tR\velementName\x12%\n" +
	"\x0einstance_count\x18\x03 \x01(\x05R\rinstanceCount\x120\n" +
	"\x14avg_duration_seconds\x18\x04 \x01(\x01R\x12avgDurationSeconds\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\"?\n" +
	"\x12GetHeatmapResponse\x12)\n" +
	"\x05steps\x18\x01 \x03(\v2\x13.bpm.v1.HeatmapStepR\x05steps\"\xf4\x01\n" +
	"\x10TemplateVariable\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rvariable_name\x18\x02 \x01(\tR\fvariableName\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12!\n" +
	"\fsource_field\x18\x04 \x01(\tR\vsourceField\x12@\n" +
	"\x0fresolver_config\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x0eresolverConfig\x12%\n" +
	"\x0efallback_value\x18\x06 \x01(\tR\rfallbackValue\"\xcd\x02\n" +
	"\bTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x15process_definition_id\x18\x02 \x01(\tR\x13processDefinitionId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rtemplate_text\x18\x04 \x01(\tR\ftemplateText\x12\x16\n" +
	"\x06module\x18\x05 \x01(\tR\x06module\x126\n" +
	"\tvariables\x18\x06 \x03(\v2\x18.bpm.v1.TemplateVariableR\tvariables\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb8\x01\n" +
	"\x14ListTemplatesRequest\x122\n" +
	"\x15process_definition_id\x18\x01 \x01(\tR\x13processDefinitionId\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"o\n" +
	"\x15ListTemplatesResponse\x12.\n" +
	"\ttemplates\x18\x01 \x03(\v2\x10.bpm.v1.TemplateR\ttemplates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd4\x01\n" +
	"\x15CreateTemplateRequest\x122\n" +
	"\x15process_definition_id\x18\x01 \x01(\tR\x13processDefinitionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rtemplate_text\x18\x03 \x01(\tR\ftemplateText\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x126\n" +
	"\tvariables\x18\x05 \x03(\v2\x18.bpm.v1.TemplateVariableR\tvariables\"\xb0\x01\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rtemplate_text\x18\x03 \x01(\tR\ftemplateText\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x126\n" +
	"\tvariables\x18\x05 \x03(\v2\x18.bpm.v1.TemplateVariableR\tvariables\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x10\n" +
	"\x0eDeleteResponse\"H\n" +
	"\x15RenderTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"\xa4\x01\n" +
	"\x10ResolvedVariable\x12#\n" +
	"\rvariable_name\x18\x01 \x01(\tR\fvariableName\x12%\n" +
	"\x0eresolved_value\x18\x02 \x01(\tR\rresolvedValue\x12#\n" +
	"\rused_fallback\x18\x03 \x01(\bR\fusedFallback\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\"\x86\x01\n" +
	"\x16RenderTemplateResponse\x12#\n" +
	"\rrendered_text\x18\x01 \x01(\tR\frenderedText\x12G\n" +
	"\x12resolved_variables\x18\x02 \x03(\v2\x18.bpm.v1.ResolvedVariableR\x11resolvedVariables\"\x1c\n" +
	"\x1aListVariableSourcesRequest\"Z\n" +
	"\x0eVariableSource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"O\n" +
	"\x1bListVariableSourcesResponse\x120\n" +
	"\asources\x18\x01 \x03(\v2\x16.bpm.v1.VariableSourceR\asources\"\x94\x02\n" +
	"\x1fConfigureVariableMappingRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12#\n" +
	"\rvariable_name\x18\x02 \x01(\tR\fvariableName\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12!\n" +
	"\fsource_field\x18\x04 \x01(\tR\vsourceField\x12@\n" +
	"\x0fresolver_config\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x0eresolverConfig\x12%\n" +
	"\x0efallback_value\x18\x06 \x01(\tR\rfallbackValue\"\x94\x02\n" +
	"\x0fVariableMapping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12#\n" +
	"\rvariable_name\x18\x03 \x01(\tR\fvariableName\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12!\n" +
	"\fsource_field\x18\x05 \x01(\tR\vsourceField\x12@\n" +
	"\x0fresolver_config\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x0eresolverConfig\x12%\n" +
	"\x0efallback_value\x18\a \x01(\tR\rfallbackValue2\xaf\r\n" +
	"\n" +
	"BPMService\x12o\n" +
	"\x0fListDefinitions\x12\x1e.bpm.v1.ListDefinitionsRequest\x1a\x1f.bpm.v1.ListDefinitionsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/bpm/definitions\x12c\n" +
	"\rGetDefinition\x12\x1c.bpm.v1.GetDefinitionRequest\x1a\x12.bpm.v1.Definition\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/bpm/definitions/{id}\x12\x80\x01\n" +
	"\x14GetDefinitionDiagram\x12#.bpm.v1.GetDefinitionDiagramRequest\x1a\x19.bpm.v1.DefinitionDiagram\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/bpm/definitions/{id}/diagram\x12n\n" +
	"\x10DeployDefinition\x12\x1f.bpm.v1.DeployDefinitionRequest\x1a\x12.bpm.v1.Definition\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/bpm/definitions/deploy\x12g\n" +
	"\rListInstances\x12\x1c.bpm.v1.ListInstancesRequest\x1a\x1d.bpm.v1.ListInstancesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/bpm/instances\x12a\n" +
	"\vGetInstance\x12\x1a.bpm.v1.GetInstanceRequest\x1a\x16.bpm.v1.InstanceDetail\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/bpm/instances/{id}\x12\x7f\n" +
	"\x11GetInstanceEvents\x12 .bpm.v1.GetInstanceEventsRequest\x1a!.bpm.v1.GetInstanceEventsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/bpm/instances/{id}/events\x12\\\n" +
	"\n" +
	"GetHeatmap\x12\x19.bpm.v1.GetHeatmapRequest\x1a\x1a.bpm.v1.GetHeatmapResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/bpm/heatmap\x12g\n" +
	"\rListTemplates\x12\x1c.bpm.v1.ListTemplatesRequest\x1a\x1d.bpm.v1.ListTemplatesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/bpm/templates\x12_\n" +
	"\x0eCreateTemplate\x12\x1d.bpm.v1.CreateTemplateRequest\x1a\x10.bpm.v1.Template\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/bpm/templates\x12d\n" +
	"\x0eUpdateTemplate\x12\x1d.bpm.v1.UpdateTemplateRequest\x1a\x10.bpm.v1.Template\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/v1/bpm/templates/{id}\x12g\n" +
	"\x0eDeleteTemplate\x12\x1d.bpm.v1.DeleteTemplateRequest\x1a\x16.bpm.v1.DeleteResponse\"\x1e\x82\xd3\xe4\x93\x02\x18*\x16/v1/bpm/templates/{id}\x12v\n" +
	"\x0eRenderTemplate\x12\x1d.bpm.v1.RenderTemplateRequest\x1a\x1e.bpm.v1.RenderTemplateResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/bpm/templates/{id}/render\x12\x8b\x01\n" +
	"\x13ListVariableSources\x12\".bpm.v1.ListVariableSourcesRequest\x1a#.bpm.v1.ListVariableSourcesResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/bpm/templates/variables/sources\x12\x8d\x01\n" +
	"\x18ConfigureVariableMapping\x12'.bpm.v1.ConfigureVariableMappingRequest\x1a\x17.bpm.v1.VariableMapping\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/bpm/templates/variables/mappingsBIZGgithub.com/arda-labs/arda/arda-be-go/services/bpm-service/api/bpm/v1;v1b\x06proto3"

var (
	file_bpm_v1_bpm_proto_rawDescOnce sync.Once
	file_bpm_v1_bpm_proto_rawDescData []byte
)

func file_bpm_v1_bpm_proto_rawDescGZIP() []byte {
	file_bpm_v1_bpm_proto_rawDescOnce.Do(func() {
		file_bpm_v1_bpm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bpm_v1_bpm_proto_rawDesc), len(file_bpm_v1_bpm_proto_rawDesc)))
	})
	return file_bpm_v1_bpm_proto_rawDescData
}

var file_bpm_v1_bpm_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_bpm_v1_bpm_proto_goTypes = []any{
	(*Definition)(nil),                      // 0: bpm.v1.Definition
	(*ListDefinitionsRequest)(nil),          // 1: bpm.v1.ListDefinitionsRequest
	(*ListDefinitionsResponse)(nil),         // 2: bpm.v1.ListDefinitionsResponse
	(*GetDefinitionRequest)(nil),            // 3: bpm.v1.GetDefinitionRequest
	(*GetDefinitionDiagramRequest)(nil),     // 4: bpm.v1.GetDefinitionDiagramRequest
	(*DefinitionDiagram)(nil),               // 5: bpm.v1.DefinitionDiagram
	(*DeployDefinitionRequest)(nil),         // 6: bpm.v1.DeployDefinitionRequest
	(*InstanceSummary)(nil),                 // 7: bpm.v1.InstanceSummary
	(*InstanceDetail)(nil),                  // 8: bpm.v1.InstanceDetail
	(*ListInstancesRequest)(nil),            // 9: bpm.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil),           // 10: bpm.v1.ListInstancesResponse
	(*GetInstanceRequest)(nil),              // 11: bpm.v1.GetInstanceRequest
	(*GetInstanceEventsRequest)(nil),        // 12: bpm.v1.GetInstanceEventsRequest
	(*ProcessEvent)(nil),                    // 13: bpm.v1.ProcessEvent
	(*GetInstanceEventsResponse)(nil),       // 14: bpm.v1.GetInstanceEventsResponse
	(*GetHeatmapRequest)(nil),               // 15: bpm.v1.GetHeatmapRequest
	(*HeatmapStep)(nil),                     // 16: bpm.v1.HeatmapStep
	(*GetHeatmapResponse)(nil),              // 17: bpm.v1.GetHeatmapResponse
	(*TemplateVariable)(nil),                // 18: bpm.v1.TemplateVariable
	(*Template)(nil),                        // 19: bpm.v1.Template
	(*ListTemplatesRequest)(nil),            // 20: bpm.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),           // 21: bpm.v1.ListTemplatesResponse
	(*CreateTemplateRequest)(nil),           // 22: bpm.v1.CreateTemplateRequest
	(*UpdateTemplateRequest)(nil),           // 23: bpm.v1.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),           // 24: bpm.v1.DeleteTemplateRequest
	(*DeleteResponse)(nil),                  // 25: bpm.v1.DeleteResponse
	(*RenderTemplateRequest)(nil),           // 26: bpm.v1.RenderTemplateRequest
	(*ResolvedVariable)(nil),                // 27: bpm.v1.ResolvedVariable
	(*RenderTemplateResponse)(nil),          // 28: bpm.v1.RenderTemplateResponse
	(*ListVariableSourcesRequest)(nil),      // 29: bpm.v1.ListVariableSourcesRequest
	(*VariableSource)(nil),                  // 30: bpm.v1.VariableSource
	(*ListVariableSourcesResponse)(nil),     // 31: bpm.v1.ListVariableSourcesResponse
	(*ConfigureVariableMappingRequest)(nil), // 32: bpm.v1.ConfigureVariableMappingRequest
	(*VariableMapping)(nil),                 // 33: bpm.v1.VariableMapping
	(*timestamppb.Timestamp)(nil),           // 34: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                 // 35: google.protobuf.Struct
}
var file_bpm_v1_bpm_proto_depIdxs = []int32{
	34, // 0: bpm.v1.Definition.created_at:type_name -> google.protobuf.Timestamp
	34, // 1: bpm.v1.Definition.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: bpm.v1.ListDefinitionsResponse.definitions:type_name -> bpm.v1.Definition
	34, // 3: bpm.v1.InstanceSummary.created_at:type_name -> google.protobuf.Timestamp
	34, // 4: bpm.v1.InstanceSummary.completed_at:type_name -> google.protobuf.Timestamp
	35, // 5: bpm.v1.InstanceDetail.variables:type_name -> google.protobuf.Struct
	34, // 6: bpm.v1.InstanceDetail.created_at:type_name -> google.protobuf.Timestamp
	34, // 7: bpm.v1.InstanceDetail.completed_at:type_name -> google.protobuf.Timestamp
	7,  // 8: bpm.v1.ListInstancesResponse.instances:type_name -> bpm.v1.InstanceSummary
	35, // 9: bpm.v1.ProcessEvent.data:type_name -> google.protobuf.Struct
	34, // 10: bpm.v1.ProcessEvent.timestamp:type_name -> google.protobuf.Timestamp
	13, // 11: bpm.v1.GetInstanceEventsResponse.events:type_name -> bpm.v1.ProcessEvent
	16, // 12: bpm.v1.GetHeatmapResponse.steps:type_name -> bpm.v1.HeatmapStep
	35, // 13: bpm.v1.TemplateVariable.resolver_config:type_name -> google.protobuf.Struct
	18, // 14: bpm.v1.Template.variables:type_name -> bpm.v1.TemplateVariable
	34, // 15: bpm.v1.Template.created_at:type_name -> google.protobuf.Timestamp
	34, // 16: bpm.v1.Template.updated_at:type_name -> google.protobuf.Timestamp
	19, // 17: bpm.v1.ListTemplatesResponse.templates:type_name -> bpm.v1.Template
	18, // 18: bpm.v1.CreateTemplateRequest.variables:type_name -> bpm.v1.TemplateVariable
	18, // 19: bpm.v1.UpdateTemplateRequest.variables:type_name -> bpm.v1.TemplateVariable
	27, // 20: bpm.v1.RenderTemplateResponse.resolved_variables:type_name -> bpm.v1.ResolvedVariable
	30, // 21: bpm.v1.ListVariableSourcesResponse.sources:type_name -> bpm.v1.VariableSource
	35, // 22: bpm.v1.ConfigureVariableMappingRequest.resolver_config:type_name -> google.protobuf.Struct
	35, // 23: bpm.v1.VariableMapping.resolver_config:type_name -> google.protobuf.Struct
	1,  // 24: bpm.v1.BPMService.ListDefinitions:input_type -> bpm.v1.ListDefinitionsRequest
	3,  // 25: bpm.v1.BPMService.GetDefinition:input_type -> bpm.v1.GetDefinitionRequest
	4,  // 26: bpm.v1.BPMService.GetDefinitionDiagram:input_type -> bpm.v1.GetDefinitionDiagramRequest
	6,  // 27: bpm.v1.BPMService.DeployDefinition:input_type -> bpm.v1.DeployDefinitionRequest
	9,  // 28: bpm.v1.BPMService.ListInstances:input_type -> bpm.v1.ListInstancesRequest
	11, // 29: bpm.v1.BPMService.GetInstance:input_type -> bpm.v1.GetInstanceRequest
	12, // 30: bpm.v1.BPMService.GetInstanceEvents:input_type -> bpm.v1.GetInstanceEventsRequest
	15, // 31: bpm.v1.BPMService.GetHeatmap:input_type -> bpm.v1.GetHeatmapRequest
	20, // 32: bpm.v1.BPMService.ListTemplates:input_type -> bpm.v1.ListTemplatesRequest
	22, // 33: bpm.v1.BPMService.CreateTemplate:input_type -> bpm.v1.CreateTemplateRequest
	23, // 34: bpm.v1.BPMService.UpdateTemplate:input_type -> bpm.v1.UpdateTemplateRequest
	24, // 35: bpm.v1.BPMService.DeleteTemplate:input_type -> bpm.v1.DeleteTemplateRequest
	26, // 36: bpm.v1.BPMService.RenderTemplate:input_type -> bpm.v1.RenderTemplateRequest
	29, // 37: bpm.v1.BPMService.ListVariableSources:input_type -> bpm.v1.ListVariableSourcesRequest
	32, // 38: bpm.v1.BPMService.ConfigureVariableMapping:input_type -> bpm.v1.ConfigureVariableMappingRequest
	2,  // 39: bpm.v1.BPMService.ListDefinitions:output_type -> bpm.v1.ListDefinitionsResponse
	0,  // 40: bpm.v1.BPMService.GetDefinition:output_type -> bpm.v1.Definition
	5,  // 41: bpm.v1.BPMService.GetDefinitionDiagram:output_type -> bpm.v1.DefinitionDiagram
	0,  // 42: bpm.v1.BPMService.DeployDefinition:output_type -> bpm.v1.Definition
	10, // 43: bpm.v1.BPMService.ListInstances:output_type -> bpm.v1.ListInstancesResponse
	8,  // 44: bpm.v1.BPMService.GetInstance:output_type -> bpm.v1.InstanceDetail
	14, // 45: bpm.v1.BPMService.GetInstanceEvents:output_type -> bpm.v1.GetInstanceEventsResponse
	17, // 46: bpm.v1.BPMService.GetHeatmap:output_type -> bpm.v1.GetHeatmapResponse
	21, // 47: bpm.v1.BPMService.ListTemplates:output_type -> bpm.v1.ListTemplatesResponse
	19, // 48: bpm.v1.BPMService.CreateTemplate:output_type -> bpm.v1.Template
	19, // 49: bpm.v1.BPMService.UpdateTemplate:output_type -> bpm.v1.Template
	25, // 50: bpm.v1.BPMService.DeleteTemplate:output_type -> bpm.v1.DeleteResponse
	28, // 51: bpm.v1.BPMService.RenderTemplate:output_type -> bpm.v1.RenderTemplateResponse
	31, // 52: bpm.v1.BPMService.ListVariableSources:output_type -> bpm.v1.ListVariableSourcesResponse
	33, // 53: bpm.v1.BPMService.ConfigureVariableMapping:output_type -> bpm.v1.VariableMapping
	39, // [39:54] is the sub-list for method output_type
	24, // [24:39] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_bpm_v1_bpm_proto_init() }
func file_bpm_v1_bpm_proto_init() {
	if File_bpm_v1_bpm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bpm_v1_bpm_proto_rawDesc), len(file_bpm_v1_bpm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bpm_v1_bpm_proto_goTypes,
		DependencyIndexes: file_bpm_v1_bpm_proto_depIdxs,
		MessageInfos:      file_bpm_v1_bpm_proto_msgTypes,
	}.Build()
	File_bpm_v1_bpm_proto = out.File
	file_bpm_v1_bpm_proto_goTypes = nil
	file_bpm_v1_bpm_proto_depIdxs = nil
}
