// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: bpm/v1/bpm.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BPMService_ListDefinitions_FullMethodName          = "/bpm.v1.BPMService/ListDefinitions"
	BPMService_GetDefinition_FullMethodName            = "/bpm.v1.BPMService/GetDefinition"
	BPMService_GetDefinitionDiagram_FullMethodName     = "/bpm.v1.BPMService/GetDefinitionDiagram"
	BPMService_DeployDefinition_FullMethodName         = "/bpm.v1.BPMService/DeployDefinition"
	BPMService_ListInstances_FullMethodName            = "/bpm.v1.BPMService/ListInstances"
	BPMService_GetInstance_FullMethodName              = "/bpm.v1.BPMService/GetInstance"
	BPMService_GetInstanceEvents_FullMethodName        = "/bpm.v1.BPMService/GetInstanceEvents"
	BPMService_GetHeatmap_FullMethodName               = "/bpm.v1.BPMService/GetHeatmap"
	BPMService_ListTemplates_FullMethodName            = "/bpm.v1.BPMService/ListTemplates"
	BPMService_CreateTemplate_FullMethodName           = "/bpm.v1.BPMService/CreateTemplate"
	BPMService_UpdateTemplate_FullMethodName           = "/bpm.v1.BPMService/UpdateTemplate"
	BPMService_DeleteTemplate_FullMethodName           = "/bpm.v1.BPMService/DeleteTemplate"
	BPMService_RenderTemplate_FullMethodName           = "/bpm.v1.BPMService/RenderTemplate"
	BPMService_ListVariableSources_FullMethodName      = "/bpm.v1.BPMService/ListVariableSources"
	BPMService_ConfigureVariableMapping_FullMethodName = "/bpm.v1.BPMService/ConfigureVariableMapping"
)

// BPMServiceClient is the client API for BPMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BPMServiceClient interface {
	// Process Definitions
	ListDefinitions(ctx context.Context, in *ListDefinitionsRequest, opts ...grpc.CallOption) (*ListDefinitionsResponse, error)
	GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*Definition, error)
	GetDefinitionDiagram(ctx context.Context, in *GetDefinitionDiagramRequest, opts ...grpc.CallOption) (*DefinitionDiagram, error)
	DeployDefinition(ctx context.Context, in *DeployDefinitionRequest, opts ...grpc.CallOption) (*Definition, error)
	// Process Instances
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceDetail, error)
	GetInstanceEvents(ctx context.Context, in *GetInstanceEventsRequest, opts ...grpc.CallOption) (*GetInstanceEventsResponse, error)
	GetHeatmap(ctx context.Context, in *GetHeatmapRequest, opts ...grpc.CallOption) (*GetHeatmapResponse, error)
	// Templates
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*Template, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderTemplateResponse, error)
	ListVariableSources(ctx context.Context, in *ListVariableSourcesRequest, opts ...grpc.CallOption) (*ListVariableSourcesResponse, error)
	ConfigureVariableMapping(ctx context.Context, in *ConfigureVariableMappingRequest, opts ...grpc.CallOption) (*VariableMapping, error)
}

type bPMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBPMServiceClient(cc grpc.ClientConnInterface) BPMServiceClient {
	return &bPMServiceClient{cc}
}

func (c *bPMServiceClient) ListDefinitions(ctx context.Context, in *ListDefinitionsRequest, opts ...grpc.CallOption) (*ListDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDefinitionsResponse)
	err := c.cc.Invoke(ctx, BPMService_ListDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*Definition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Definition)
	err := c.cc.Invoke(ctx, BPMService_GetDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) GetDefinitionDiagram(ctx context.Context, in *GetDefinitionDiagramRequest, opts ...grpc.CallOption) (*DefinitionDiagram, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefinitionDiagram)
	err := c.cc.Invoke(ctx, BPMService_GetDefinitionDiagram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) DeployDefinition(ctx context.Context, in *DeployDefinitionRequest, opts ...grpc.CallOption) (*Definition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Definition)
	err := c.cc.Invoke(ctx, BPMService_DeployDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, BPMService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceDetail)
	err := c.cc.Invoke(ctx, BPMService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) GetInstanceEvents(ctx context.Context, in *GetInstanceEventsRequest, opts ...grpc.CallOption) (*GetInstanceEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceEventsResponse)
	err := c.cc.Invoke(ctx, BPMService_GetInstanceEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) GetHeatmap(ctx context.Context, in *GetHeatmapRequest, opts ...grpc.CallOption) (*GetHeatmapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHeatmapResponse)
	err := c.cc.Invoke(ctx, BPMService_GetHeatmap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, BPMService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, BPMService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*Template, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Template)
	err := c.cc.Invoke(ctx, BPMService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, BPMService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) RenderTemplate(ctx context.Context, in *RenderTemplateRequest, opts ...grpc.CallOption) (*RenderTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderTemplateResponse)
	err := c.cc.Invoke(ctx, BPMService_RenderTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) ListVariableSources(ctx context.Context, in *ListVariableSourcesRequest, opts ...grpc.CallOption) (*ListVariableSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVariableSourcesResponse)
	err := c.cc.Invoke(ctx, BPMService_ListVariableSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bPMServiceClient) ConfigureVariableMapping(ctx context.Context, in *ConfigureVariableMappingRequest, opts ...grpc.CallOption) (*VariableMapping, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariableMapping)
	err := c.cc.Invoke(ctx, BPMService_ConfigureVariableMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BPMServiceServer is the server API for BPMService service.
// All implementations must embed UnimplementedBPMServiceServer
// for forward compatibility.
type BPMServiceServer interface {
	// Process Definitions
	ListDefinitions(context.Context, *ListDefinitionsRequest) (*ListDefinitionsResponse, error)
	GetDefinition(context.Context, *GetDefinitionRequest) (*Definition, error)
	GetDefinitionDiagram(context.Context, *GetDefinitionDiagramRequest) (*DefinitionDiagram, error)
	DeployDefinition(context.Context, *DeployDefinitionRequest) (*Definition, error)
	// Process Instances
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	GetInstance(context.Context, *GetInstanceRequest) (*InstanceDetail, error)
	GetInstanceEvents(context.Context, *GetInstanceEventsRequest) (*GetInstanceEventsResponse, error)
	GetHeatmap(context.Context, *GetHeatmapRequest) (*GetHeatmapResponse, error)
	// Templates
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	CreateTemplate(context.Context, *CreateTemplateRequest) (*Template, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*Template, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteResponse, error)
	RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderTemplateResponse, error)
	ListVariableSources(context.Context, *ListVariableSourcesRequest) (*ListVariableSourcesResponse, error)
	ConfigureVariableMapping(context.Context, *ConfigureVariableMappingRequest) (*VariableMapping, error)
	mustEmbedUnimplementedBPMServiceServer()
}

// UnimplementedBPMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBPMServiceServer struct{}

func (UnimplementedBPMServiceServer) ListDefinitions(context.Context, *ListDefinitionsRequest) (*ListDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDefinitions not implemented")
}
func (UnimplementedBPMServiceServer) GetDefinition(context.Context, *GetDefinitionRequest) (*Definition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefinition not implemented")
}
func (UnimplementedBPMServiceServer) GetDefinitionDiagram(context.Context, *GetDefinitionDiagramRequest) (*DefinitionDiagram, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefinitionDiagram not implemented")
}
func (UnimplementedBPMServiceServer) DeployDefinition(context.Context, *DeployDefinitionRequest) (*Definition, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployDefinition not implemented")
}
func (UnimplementedBPMServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedBPMServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*InstanceDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedBPMServiceServer) GetInstanceEvents(context.Context, *GetInstanceEventsRequest) (*GetInstanceEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceEvents not implemented")
}
func (UnimplementedBPMServiceServer) GetHeatmap(context.Context, *GetHeatmapRequest) (*GetHeatmapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeatmap not implemented")
}
func (UnimplementedBPMServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedBPMServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*Template, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedBPMServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*Template, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedBPMServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedBPMServiceServer) RenderTemplate(context.Context, *RenderTemplateRequest) (*RenderTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderTemplate not implemented")
}
func (UnimplementedBPMServiceServer) ListVariableSources(context.Context, *ListVariableSourcesRequest) (*ListVariableSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVariableSources not implemented")
}
func (UnimplementedBPMServiceServer) ConfigureVariableMapping(context.Context, *ConfigureVariableMappingRequest) (*VariableMapping, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureVariableMapping not implemented")
}
func (UnimplementedBPMServiceServer) mustEmbedUnimplementedBPMServiceServer() {}
func (UnimplementedBPMServiceServer) testEmbeddedByValue()                    {}

// UnsafeBPMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BPMServiceServer will
// result in compilation errors.
type UnsafeBPMServiceServer interface {
	mustEmbedUnimplementedBPMServiceServer()
}

func RegisterBPMServiceServer(s grpc.ServiceRegistrar, srv BPMServiceServer) {
	// If the following call panics, it indicates UnimplementedBPMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BPMService_ServiceDesc, srv)
}

func _BPMService_ListDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).ListDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_ListDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).ListDefinitions(ctx, req.(*ListDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_GetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).GetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_GetDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).GetDefinition(ctx, req.(*GetDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_GetDefinitionDiagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefinitionDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).GetDefinitionDiagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_GetDefinitionDiagram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).GetDefinitionDiagram(ctx, req.(*GetDefinitionDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_DeployDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).DeployDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_DeployDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).DeployDefinition(ctx, req.(*DeployDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_GetInstanceEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).GetInstanceEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_GetInstanceEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).GetInstanceEvents(ctx, req.(*GetInstanceEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_GetHeatmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHeatmapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).GetHeatmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_GetHeatmap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).GetHeatmap(ctx, req.(*GetHeatmapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_RenderTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).RenderTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_RenderTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).RenderTemplate(ctx, req.(*RenderTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_ListVariableSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVariableSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).ListVariableSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_ListVariableSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).ListVariableSources(ctx, req.(*ListVariableSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BPMService_ConfigureVariableMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureVariableMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BPMServiceServer).ConfigureVariableMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BPMService_ConfigureVariableMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BPMServiceServer).ConfigureVariableMapping(ctx, req.(*ConfigureVariableMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BPMService_ServiceDesc is the grpc.ServiceDesc for BPMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BPMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bpm.v1.BPMService",
	HandlerType: (*BPMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDefinitions",
			Handler:    _BPMService_ListDefinitions_Handler,
		},
		{
			MethodName: "GetDefinition",
			Handler:    _BPMService_GetDefinition_Handler,
		},
		{
			MethodName: "GetDefinitionDiagram",
			Handler:    _BPMService_GetDefinitionDiagram_Handler,
		},
		{
			MethodName: "DeployDefinition",
			Handler:    _BPMService_DeployDefinition_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _BPMService_ListInstances_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _BPMService_GetInstance_Handler,
		},
		{
			MethodName: "GetInstanceEvents",
			Handler:    _BPMService_GetInstanceEvents_Handler,
		},
		{
			MethodName: "GetHeatmap",
			Handler:    _BPMService_GetHeatmap_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _BPMService_ListTemplates_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _BPMService_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _BPMService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _BPMService_DeleteTemplate_Handler,
		},
		{
			MethodName: "RenderTemplate",
			Handler:    _BPMService_RenderTemplate_Handler,
		},
		{
			MethodName: "ListVariableSources",
			Handler:    _BPMService_ListVariableSources_Handler,
		},
		{
			MethodName: "ConfigureVariableMapping",
			Handler:    _BPMService_ConfigureVariableMapping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bpm/v1/bpm.proto",
}
