// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: mdm/v1/mdm.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MdmService_ListAdministrativeUnits_FullMethodName               = "/mdm.v1.MdmService/ListAdministrativeUnits"
	MdmService_ListAdministrativeUnitTree_FullMethodName            = "/mdm.v1.MdmService/ListAdministrativeUnitTree"
	MdmService_ListProvinces_FullMethodName                         = "/mdm.v1.MdmService/ListProvinces"
	MdmService_ListWards_FullMethodName                             = "/mdm.v1.MdmService/ListWards"
	MdmService_GetAdministrativeUnit_FullMethodName                 = "/mdm.v1.MdmService/GetAdministrativeUnit"
	MdmService_CreateAdministrativeUnit_FullMethodName              = "/mdm.v1.MdmService/CreateAdministrativeUnit"
	MdmService_UpdateAdministrativeUnit_FullMethodName              = "/mdm.v1.MdmService/UpdateAdministrativeUnit"
	MdmService_DeleteAdministrativeUnit_FullMethodName              = "/mdm.v1.MdmService/DeleteAdministrativeUnit"
	MdmService_SyncAdministrativeUnitsFromAddressKit_FullMethodName = "/mdm.v1.MdmService/SyncAdministrativeUnitsFromAddressKit"
	MdmService_ListAreaTypes_FullMethodName                         = "/mdm.v1.MdmService/ListAreaTypes"
	MdmService_GetAreaType_FullMethodName                           = "/mdm.v1.MdmService/GetAreaType"
	MdmService_CreateAreaType_FullMethodName                        = "/mdm.v1.MdmService/CreateAreaType"
	MdmService_UpdateAreaType_FullMethodName                        = "/mdm.v1.MdmService/UpdateAreaType"
	MdmService_DeleteAreaType_FullMethodName                        = "/mdm.v1.MdmService/DeleteAreaType"
	MdmService_ListAreas_FullMethodName                             = "/mdm.v1.MdmService/ListAreas"
	MdmService_ListAreaTree_FullMethodName                          = "/mdm.v1.MdmService/ListAreaTree"
	MdmService_GetArea_FullMethodName                               = "/mdm.v1.MdmService/GetArea"
	MdmService_CreateArea_FullMethodName                            = "/mdm.v1.MdmService/CreateArea"
	MdmService_UpdateArea_FullMethodName                            = "/mdm.v1.MdmService/UpdateArea"
	MdmService_DeleteArea_FullMethodName                            = "/mdm.v1.MdmService/DeleteArea"
	MdmService_AssignAreaAdministrativeUnit_FullMethodName          = "/mdm.v1.MdmService/AssignAreaAdministrativeUnit"
	MdmService_ListAreaAdministrativeUnits_FullMethodName           = "/mdm.v1.MdmService/ListAreaAdministrativeUnits"
	MdmService_RemoveAreaAdministrativeUnit_FullMethodName          = "/mdm.v1.MdmService/RemoveAreaAdministrativeUnit"
	MdmService_ListCodeSets_FullMethodName                          = "/mdm.v1.MdmService/ListCodeSets"
	MdmService_GetCodeSet_FullMethodName                            = "/mdm.v1.MdmService/GetCodeSet"
	MdmService_CreateCodeSet_FullMethodName                         = "/mdm.v1.MdmService/CreateCodeSet"
	MdmService_UpdateCodeSet_FullMethodName                         = "/mdm.v1.MdmService/UpdateCodeSet"
	MdmService_DeleteCodeSet_FullMethodName                         = "/mdm.v1.MdmService/DeleteCodeSet"
	MdmService_ListCodeItems_FullMethodName                         = "/mdm.v1.MdmService/ListCodeItems"
	MdmService_GetCodeItem_FullMethodName                           = "/mdm.v1.MdmService/GetCodeItem"
	MdmService_CreateCodeItem_FullMethodName                        = "/mdm.v1.MdmService/CreateCodeItem"
	MdmService_UpdateCodeItem_FullMethodName                        = "/mdm.v1.MdmService/UpdateCodeItem"
	MdmService_DeleteCodeItem_FullMethodName                        = "/mdm.v1.MdmService/DeleteCodeItem"
	MdmService_ListSystemParameters_FullMethodName                  = "/mdm.v1.MdmService/ListSystemParameters"
	MdmService_GetSystemParameter_FullMethodName                    = "/mdm.v1.MdmService/GetSystemParameter"
	MdmService_CreateSystemParameter_FullMethodName                 = "/mdm.v1.MdmService/CreateSystemParameter"
	MdmService_UpdateSystemParameter_FullMethodName                 = "/mdm.v1.MdmService/UpdateSystemParameter"
	MdmService_DeleteSystemParameter_FullMethodName                 = "/mdm.v1.MdmService/DeleteSystemParameter"
	MdmService_ListCreditInstitutions_FullMethodName                = "/mdm.v1.MdmService/ListCreditInstitutions"
	MdmService_GetCreditInstitution_FullMethodName                  = "/mdm.v1.MdmService/GetCreditInstitution"
	MdmService_CreateCreditInstitution_FullMethodName               = "/mdm.v1.MdmService/CreateCreditInstitution"
	MdmService_UpdateCreditInstitution_FullMethodName               = "/mdm.v1.MdmService/UpdateCreditInstitution"
	MdmService_DeleteCreditInstitution_FullMethodName               = "/mdm.v1.MdmService/DeleteCreditInstitution"
)

// MdmServiceClient is the client API for MdmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MdmServiceClient interface {
	ListAdministrativeUnits(ctx context.Context, in *ListAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitsResponse, error)
	ListAdministrativeUnitTree(ctx context.Context, in *ListAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitTreeResponse, error)
	ListProvinces(ctx context.Context, in *ListAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitsResponse, error)
	ListWards(ctx context.Context, in *ListWardsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitsResponse, error)
	GetAdministrativeUnit(ctx context.Context, in *GetAdministrativeUnitRequest, opts ...grpc.CallOption) (*AdministrativeUnit, error)
	CreateAdministrativeUnit(ctx context.Context, in *CreateAdministrativeUnitRequest, opts ...grpc.CallOption) (*AdministrativeUnit, error)
	UpdateAdministrativeUnit(ctx context.Context, in *UpdateAdministrativeUnitRequest, opts ...grpc.CallOption) (*AdministrativeUnit, error)
	DeleteAdministrativeUnit(ctx context.Context, in *DeleteAdministrativeUnitRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	SyncAdministrativeUnitsFromAddressKit(ctx context.Context, in *SyncAdministrativeUnitsFromAddressKitRequest, opts ...grpc.CallOption) (*SyncAdministrativeUnitsFromAddressKitResponse, error)
	ListAreaTypes(ctx context.Context, in *ListAreaTypesRequest, opts ...grpc.CallOption) (*ListAreaTypesResponse, error)
	GetAreaType(ctx context.Context, in *GetAreaTypeRequest, opts ...grpc.CallOption) (*AreaType, error)
	CreateAreaType(ctx context.Context, in *CreateAreaTypeRequest, opts ...grpc.CallOption) (*AreaType, error)
	UpdateAreaType(ctx context.Context, in *UpdateAreaTypeRequest, opts ...grpc.CallOption) (*AreaType, error)
	DeleteAreaType(ctx context.Context, in *DeleteAreaTypeRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListAreas(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreasResponse, error)
	ListAreaTree(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreaTreeResponse, error)
	GetArea(ctx context.Context, in *GetAreaRequest, opts ...grpc.CallOption) (*Area, error)
	CreateArea(ctx context.Context, in *CreateAreaRequest, opts ...grpc.CallOption) (*Area, error)
	UpdateArea(ctx context.Context, in *UpdateAreaRequest, opts ...grpc.CallOption) (*Area, error)
	DeleteArea(ctx context.Context, in *DeleteAreaRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	AssignAreaAdministrativeUnit(ctx context.Context, in *AssignAreaAdministrativeUnitRequest, opts ...grpc.CallOption) (*AreaAdministrativeUnit, error)
	ListAreaAdministrativeUnits(ctx context.Context, in *ListAreaAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAreaAdministrativeUnitsResponse, error)
	RemoveAreaAdministrativeUnit(ctx context.Context, in *RemoveAreaAdministrativeUnitRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListCodeSets(ctx context.Context, in *ListCodeSetsRequest, opts ...grpc.CallOption) (*ListCodeSetsResponse, error)
	GetCodeSet(ctx context.Context, in *GetCodeSetRequest, opts ...grpc.CallOption) (*CodeSet, error)
	CreateCodeSet(ctx context.Context, in *CreateCodeSetRequest, opts ...grpc.CallOption) (*CodeSet, error)
	UpdateCodeSet(ctx context.Context, in *UpdateCodeSetRequest, opts ...grpc.CallOption) (*CodeSet, error)
	DeleteCodeSet(ctx context.Context, in *DeleteCodeSetRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListCodeItems(ctx context.Context, in *ListCodeItemsRequest, opts ...grpc.CallOption) (*ListCodeItemsResponse, error)
	GetCodeItem(ctx context.Context, in *GetCodeItemRequest, opts ...grpc.CallOption) (*CodeItem, error)
	CreateCodeItem(ctx context.Context, in *CreateCodeItemRequest, opts ...grpc.CallOption) (*CodeItem, error)
	UpdateCodeItem(ctx context.Context, in *UpdateCodeItemRequest, opts ...grpc.CallOption) (*CodeItem, error)
	DeleteCodeItem(ctx context.Context, in *DeleteCodeItemRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListSystemParameters(ctx context.Context, in *ListSystemParametersRequest, opts ...grpc.CallOption) (*ListSystemParametersResponse, error)
	GetSystemParameter(ctx context.Context, in *GetSystemParameterRequest, opts ...grpc.CallOption) (*SystemParameter, error)
	CreateSystemParameter(ctx context.Context, in *CreateSystemParameterRequest, opts ...grpc.CallOption) (*SystemParameter, error)
	UpdateSystemParameter(ctx context.Context, in *UpdateSystemParameterRequest, opts ...grpc.CallOption) (*SystemParameter, error)
	DeleteSystemParameter(ctx context.Context, in *DeleteSystemParameterRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	ListCreditInstitutions(ctx context.Context, in *ListCreditInstitutionsRequest, opts ...grpc.CallOption) (*ListCreditInstitutionsResponse, error)
	GetCreditInstitution(ctx context.Context, in *GetCreditInstitutionRequest, opts ...grpc.CallOption) (*CreditInstitution, error)
	CreateCreditInstitution(ctx context.Context, in *CreateCreditInstitutionRequest, opts ...grpc.CallOption) (*CreditInstitution, error)
	UpdateCreditInstitution(ctx context.Context, in *UpdateCreditInstitutionRequest, opts ...grpc.CallOption) (*CreditInstitution, error)
	DeleteCreditInstitution(ctx context.Context, in *DeleteCreditInstitutionRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type mdmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMdmServiceClient(cc grpc.ClientConnInterface) MdmServiceClient {
	return &mdmServiceClient{cc}
}

func (c *mdmServiceClient) ListAdministrativeUnits(ctx context.Context, in *ListAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdministrativeUnitsResponse)
	err := c.cc.Invoke(ctx, MdmService_ListAdministrativeUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListAdministrativeUnitTree(ctx context.Context, in *ListAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdministrativeUnitTreeResponse)
	err := c.cc.Invoke(ctx, MdmService_ListAdministrativeUnitTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListProvinces(ctx context.Context, in *ListAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdministrativeUnitsResponse)
	err := c.cc.Invoke(ctx, MdmService_ListProvinces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListWards(ctx context.Context, in *ListWardsRequest, opts ...grpc.CallOption) (*ListAdministrativeUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdministrativeUnitsResponse)
	err := c.cc.Invoke(ctx, MdmService_ListWards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) GetAdministrativeUnit(ctx context.Context, in *GetAdministrativeUnitRequest, opts ...grpc.CallOption) (*AdministrativeUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdministrativeUnit)
	err := c.cc.Invoke(ctx, MdmService_GetAdministrativeUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) CreateAdministrativeUnit(ctx context.Context, in *CreateAdministrativeUnitRequest, opts ...grpc.CallOption) (*AdministrativeUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdministrativeUnit)
	err := c.cc.Invoke(ctx, MdmService_CreateAdministrativeUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) UpdateAdministrativeUnit(ctx context.Context, in *UpdateAdministrativeUnitRequest, opts ...grpc.CallOption) (*AdministrativeUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdministrativeUnit)
	err := c.cc.Invoke(ctx, MdmService_UpdateAdministrativeUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) DeleteAdministrativeUnit(ctx context.Context, in *DeleteAdministrativeUnitRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_DeleteAdministrativeUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) SyncAdministrativeUnitsFromAddressKit(ctx context.Context, in *SyncAdministrativeUnitsFromAddressKitRequest, opts ...grpc.CallOption) (*SyncAdministrativeUnitsFromAddressKitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncAdministrativeUnitsFromAddressKitResponse)
	err := c.cc.Invoke(ctx, MdmService_SyncAdministrativeUnitsFromAddressKit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListAreaTypes(ctx context.Context, in *ListAreaTypesRequest, opts ...grpc.CallOption) (*ListAreaTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAreaTypesResponse)
	err := c.cc.Invoke(ctx, MdmService_ListAreaTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) GetAreaType(ctx context.Context, in *GetAreaTypeRequest, opts ...grpc.CallOption) (*AreaType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreaType)
	err := c.cc.Invoke(ctx, MdmService_GetAreaType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) CreateAreaType(ctx context.Context, in *CreateAreaTypeRequest, opts ...grpc.CallOption) (*AreaType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreaType)
	err := c.cc.Invoke(ctx, MdmService_CreateAreaType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) UpdateAreaType(ctx context.Context, in *UpdateAreaTypeRequest, opts ...grpc.CallOption) (*AreaType, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreaType)
	err := c.cc.Invoke(ctx, MdmService_UpdateAreaType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) DeleteAreaType(ctx context.Context, in *DeleteAreaTypeRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_DeleteAreaType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListAreas(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAreasResponse)
	err := c.cc.Invoke(ctx, MdmService_ListAreas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListAreaTree(ctx context.Context, in *ListAreasRequest, opts ...grpc.CallOption) (*ListAreaTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAreaTreeResponse)
	err := c.cc.Invoke(ctx, MdmService_ListAreaTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) GetArea(ctx context.Context, in *GetAreaRequest, opts ...grpc.CallOption) (*Area, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Area)
	err := c.cc.Invoke(ctx, MdmService_GetArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) CreateArea(ctx context.Context, in *CreateAreaRequest, opts ...grpc.CallOption) (*Area, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Area)
	err := c.cc.Invoke(ctx, MdmService_CreateArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) UpdateArea(ctx context.Context, in *UpdateAreaRequest, opts ...grpc.CallOption) (*Area, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Area)
	err := c.cc.Invoke(ctx, MdmService_UpdateArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) DeleteArea(ctx context.Context, in *DeleteAreaRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_DeleteArea_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) AssignAreaAdministrativeUnit(ctx context.Context, in *AssignAreaAdministrativeUnitRequest, opts ...grpc.CallOption) (*AreaAdministrativeUnit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreaAdministrativeUnit)
	err := c.cc.Invoke(ctx, MdmService_AssignAreaAdministrativeUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListAreaAdministrativeUnits(ctx context.Context, in *ListAreaAdministrativeUnitsRequest, opts ...grpc.CallOption) (*ListAreaAdministrativeUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAreaAdministrativeUnitsResponse)
	err := c.cc.Invoke(ctx, MdmService_ListAreaAdministrativeUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) RemoveAreaAdministrativeUnit(ctx context.Context, in *RemoveAreaAdministrativeUnitRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_RemoveAreaAdministrativeUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListCodeSets(ctx context.Context, in *ListCodeSetsRequest, opts ...grpc.CallOption) (*ListCodeSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCodeSetsResponse)
	err := c.cc.Invoke(ctx, MdmService_ListCodeSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) GetCodeSet(ctx context.Context, in *GetCodeSetRequest, opts ...grpc.CallOption) (*CodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeSet)
	err := c.cc.Invoke(ctx, MdmService_GetCodeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) CreateCodeSet(ctx context.Context, in *CreateCodeSetRequest, opts ...grpc.CallOption) (*CodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeSet)
	err := c.cc.Invoke(ctx, MdmService_CreateCodeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) UpdateCodeSet(ctx context.Context, in *UpdateCodeSetRequest, opts ...grpc.CallOption) (*CodeSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeSet)
	err := c.cc.Invoke(ctx, MdmService_UpdateCodeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) DeleteCodeSet(ctx context.Context, in *DeleteCodeSetRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_DeleteCodeSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListCodeItems(ctx context.Context, in *ListCodeItemsRequest, opts ...grpc.CallOption) (*ListCodeItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCodeItemsResponse)
	err := c.cc.Invoke(ctx, MdmService_ListCodeItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) GetCodeItem(ctx context.Context, in *GetCodeItemRequest, opts ...grpc.CallOption) (*CodeItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeItem)
	err := c.cc.Invoke(ctx, MdmService_GetCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) CreateCodeItem(ctx context.Context, in *CreateCodeItemRequest, opts ...grpc.CallOption) (*CodeItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeItem)
	err := c.cc.Invoke(ctx, MdmService_CreateCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) UpdateCodeItem(ctx context.Context, in *UpdateCodeItemRequest, opts ...grpc.CallOption) (*CodeItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeItem)
	err := c.cc.Invoke(ctx, MdmService_UpdateCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) DeleteCodeItem(ctx context.Context, in *DeleteCodeItemRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_DeleteCodeItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListSystemParameters(ctx context.Context, in *ListSystemParametersRequest, opts ...grpc.CallOption) (*ListSystemParametersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSystemParametersResponse)
	err := c.cc.Invoke(ctx, MdmService_ListSystemParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) GetSystemParameter(ctx context.Context, in *GetSystemParameterRequest, opts ...grpc.CallOption) (*SystemParameter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemParameter)
	err := c.cc.Invoke(ctx, MdmService_GetSystemParameter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) CreateSystemParameter(ctx context.Context, in *CreateSystemParameterRequest, opts ...grpc.CallOption) (*SystemParameter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemParameter)
	err := c.cc.Invoke(ctx, MdmService_CreateSystemParameter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) UpdateSystemParameter(ctx context.Context, in *UpdateSystemParameterRequest, opts ...grpc.CallOption) (*SystemParameter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemParameter)
	err := c.cc.Invoke(ctx, MdmService_UpdateSystemParameter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) DeleteSystemParameter(ctx context.Context, in *DeleteSystemParameterRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_DeleteSystemParameter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) ListCreditInstitutions(ctx context.Context, in *ListCreditInstitutionsRequest, opts ...grpc.CallOption) (*ListCreditInstitutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCreditInstitutionsResponse)
	err := c.cc.Invoke(ctx, MdmService_ListCreditInstitutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) GetCreditInstitution(ctx context.Context, in *GetCreditInstitutionRequest, opts ...grpc.CallOption) (*CreditInstitution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditInstitution)
	err := c.cc.Invoke(ctx, MdmService_GetCreditInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) CreateCreditInstitution(ctx context.Context, in *CreateCreditInstitutionRequest, opts ...grpc.CallOption) (*CreditInstitution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditInstitution)
	err := c.cc.Invoke(ctx, MdmService_CreateCreditInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) UpdateCreditInstitution(ctx context.Context, in *UpdateCreditInstitutionRequest, opts ...grpc.CallOption) (*CreditInstitution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditInstitution)
	err := c.cc.Invoke(ctx, MdmService_UpdateCreditInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mdmServiceClient) DeleteCreditInstitution(ctx context.Context, in *DeleteCreditInstitutionRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, MdmService_DeleteCreditInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MdmServiceServer is the server API for MdmService service.
// All implementations must embed UnimplementedMdmServiceServer
// for forward compatibility.
type MdmServiceServer interface {
	ListAdministrativeUnits(context.Context, *ListAdministrativeUnitsRequest) (*ListAdministrativeUnitsResponse, error)
	ListAdministrativeUnitTree(context.Context, *ListAdministrativeUnitsRequest) (*ListAdministrativeUnitTreeResponse, error)
	ListProvinces(context.Context, *ListAdministrativeUnitsRequest) (*ListAdministrativeUnitsResponse, error)
	ListWards(context.Context, *ListWardsRequest) (*ListAdministrativeUnitsResponse, error)
	GetAdministrativeUnit(context.Context, *GetAdministrativeUnitRequest) (*AdministrativeUnit, error)
	CreateAdministrativeUnit(context.Context, *CreateAdministrativeUnitRequest) (*AdministrativeUnit, error)
	UpdateAdministrativeUnit(context.Context, *UpdateAdministrativeUnitRequest) (*AdministrativeUnit, error)
	DeleteAdministrativeUnit(context.Context, *DeleteAdministrativeUnitRequest) (*DeleteResponse, error)
	SyncAdministrativeUnitsFromAddressKit(context.Context, *SyncAdministrativeUnitsFromAddressKitRequest) (*SyncAdministrativeUnitsFromAddressKitResponse, error)
	ListAreaTypes(context.Context, *ListAreaTypesRequest) (*ListAreaTypesResponse, error)
	GetAreaType(context.Context, *GetAreaTypeRequest) (*AreaType, error)
	CreateAreaType(context.Context, *CreateAreaTypeRequest) (*AreaType, error)
	UpdateAreaType(context.Context, *UpdateAreaTypeRequest) (*AreaType, error)
	DeleteAreaType(context.Context, *DeleteAreaTypeRequest) (*DeleteResponse, error)
	ListAreas(context.Context, *ListAreasRequest) (*ListAreasResponse, error)
	ListAreaTree(context.Context, *ListAreasRequest) (*ListAreaTreeResponse, error)
	GetArea(context.Context, *GetAreaRequest) (*Area, error)
	CreateArea(context.Context, *CreateAreaRequest) (*Area, error)
	UpdateArea(context.Context, *UpdateAreaRequest) (*Area, error)
	DeleteArea(context.Context, *DeleteAreaRequest) (*DeleteResponse, error)
	AssignAreaAdministrativeUnit(context.Context, *AssignAreaAdministrativeUnitRequest) (*AreaAdministrativeUnit, error)
	ListAreaAdministrativeUnits(context.Context, *ListAreaAdministrativeUnitsRequest) (*ListAreaAdministrativeUnitsResponse, error)
	RemoveAreaAdministrativeUnit(context.Context, *RemoveAreaAdministrativeUnitRequest) (*DeleteResponse, error)
	ListCodeSets(context.Context, *ListCodeSetsRequest) (*ListCodeSetsResponse, error)
	GetCodeSet(context.Context, *GetCodeSetRequest) (*CodeSet, error)
	CreateCodeSet(context.Context, *CreateCodeSetRequest) (*CodeSet, error)
	UpdateCodeSet(context.Context, *UpdateCodeSetRequest) (*CodeSet, error)
	DeleteCodeSet(context.Context, *DeleteCodeSetRequest) (*DeleteResponse, error)
	ListCodeItems(context.Context, *ListCodeItemsRequest) (*ListCodeItemsResponse, error)
	GetCodeItem(context.Context, *GetCodeItemRequest) (*CodeItem, error)
	CreateCodeItem(context.Context, *CreateCodeItemRequest) (*CodeItem, error)
	UpdateCodeItem(context.Context, *UpdateCodeItemRequest) (*CodeItem, error)
	DeleteCodeItem(context.Context, *DeleteCodeItemRequest) (*DeleteResponse, error)
	ListSystemParameters(context.Context, *ListSystemParametersRequest) (*ListSystemParametersResponse, error)
	GetSystemParameter(context.Context, *GetSystemParameterRequest) (*SystemParameter, error)
	CreateSystemParameter(context.Context, *CreateSystemParameterRequest) (*SystemParameter, error)
	UpdateSystemParameter(context.Context, *UpdateSystemParameterRequest) (*SystemParameter, error)
	DeleteSystemParameter(context.Context, *DeleteSystemParameterRequest) (*DeleteResponse, error)
	ListCreditInstitutions(context.Context, *ListCreditInstitutionsRequest) (*ListCreditInstitutionsResponse, error)
	GetCreditInstitution(context.Context, *GetCreditInstitutionRequest) (*CreditInstitution, error)
	CreateCreditInstitution(context.Context, *CreateCreditInstitutionRequest) (*CreditInstitution, error)
	UpdateCreditInstitution(context.Context, *UpdateCreditInstitutionRequest) (*CreditInstitution, error)
	DeleteCreditInstitution(context.Context, *DeleteCreditInstitutionRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedMdmServiceServer()
}

// UnimplementedMdmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMdmServiceServer struct{}

func (UnimplementedMdmServiceServer) ListAdministrativeUnits(context.Context, *ListAdministrativeUnitsRequest) (*ListAdministrativeUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdministrativeUnits not implemented")
}
func (UnimplementedMdmServiceServer) ListAdministrativeUnitTree(context.Context, *ListAdministrativeUnitsRequest) (*ListAdministrativeUnitTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdministrativeUnitTree not implemented")
}
func (UnimplementedMdmServiceServer) ListProvinces(context.Context, *ListAdministrativeUnitsRequest) (*ListAdministrativeUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProvinces not implemented")
}
func (UnimplementedMdmServiceServer) ListWards(context.Context, *ListWardsRequest) (*ListAdministrativeUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWards not implemented")
}
func (UnimplementedMdmServiceServer) GetAdministrativeUnit(context.Context, *GetAdministrativeUnitRequest) (*AdministrativeUnit, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdministrativeUnit not implemented")
}
func (UnimplementedMdmServiceServer) CreateAdministrativeUnit(context.Context, *CreateAdministrativeUnitRequest) (*AdministrativeUnit, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAdministrativeUnit not implemented")
}
func (UnimplementedMdmServiceServer) UpdateAdministrativeUnit(context.Context, *UpdateAdministrativeUnitRequest) (*AdministrativeUnit, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAdministrativeUnit not implemented")
}
func (UnimplementedMdmServiceServer) DeleteAdministrativeUnit(context.Context, *DeleteAdministrativeUnitRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAdministrativeUnit not implemented")
}
func (UnimplementedMdmServiceServer) SyncAdministrativeUnitsFromAddressKit(context.Context, *SyncAdministrativeUnitsFromAddressKitRequest) (*SyncAdministrativeUnitsFromAddressKitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncAdministrativeUnitsFromAddressKit not implemented")
}
func (UnimplementedMdmServiceServer) ListAreaTypes(context.Context, *ListAreaTypesRequest) (*ListAreaTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAreaTypes not implemented")
}
func (UnimplementedMdmServiceServer) GetAreaType(context.Context, *GetAreaTypeRequest) (*AreaType, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAreaType not implemented")
}
func (UnimplementedMdmServiceServer) CreateAreaType(context.Context, *CreateAreaTypeRequest) (*AreaType, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAreaType not implemented")
}
func (UnimplementedMdmServiceServer) UpdateAreaType(context.Context, *UpdateAreaTypeRequest) (*AreaType, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAreaType not implemented")
}
func (UnimplementedMdmServiceServer) DeleteAreaType(context.Context, *DeleteAreaTypeRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAreaType not implemented")
}
func (UnimplementedMdmServiceServer) ListAreas(context.Context, *ListAreasRequest) (*ListAreasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAreas not implemented")
}
func (UnimplementedMdmServiceServer) ListAreaTree(context.Context, *ListAreasRequest) (*ListAreaTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAreaTree not implemented")
}
func (UnimplementedMdmServiceServer) GetArea(context.Context, *GetAreaRequest) (*Area, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArea not implemented")
}
func (UnimplementedMdmServiceServer) CreateArea(context.Context, *CreateAreaRequest) (*Area, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArea not implemented")
}
func (UnimplementedMdmServiceServer) UpdateArea(context.Context, *UpdateAreaRequest) (*Area, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateArea not implemented")
}
func (UnimplementedMdmServiceServer) DeleteArea(context.Context, *DeleteAreaRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArea not implemented")
}
func (UnimplementedMdmServiceServer) AssignAreaAdministrativeUnit(context.Context, *AssignAreaAdministrativeUnitRequest) (*AreaAdministrativeUnit, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignAreaAdministrativeUnit not implemented")
}
func (UnimplementedMdmServiceServer) ListAreaAdministrativeUnits(context.Context, *ListAreaAdministrativeUnitsRequest) (*ListAreaAdministrativeUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAreaAdministrativeUnits not implemented")
}
func (UnimplementedMdmServiceServer) RemoveAreaAdministrativeUnit(context.Context, *RemoveAreaAdministrativeUnitRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAreaAdministrativeUnit not implemented")
}
func (UnimplementedMdmServiceServer) ListCodeSets(context.Context, *ListCodeSetsRequest) (*ListCodeSetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCodeSets not implemented")
}
func (UnimplementedMdmServiceServer) GetCodeSet(context.Context, *GetCodeSetRequest) (*CodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCodeSet not implemented")
}
func (UnimplementedMdmServiceServer) CreateCodeSet(context.Context, *CreateCodeSetRequest) (*CodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCodeSet not implemented")
}
func (UnimplementedMdmServiceServer) UpdateCodeSet(context.Context, *UpdateCodeSetRequest) (*CodeSet, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCodeSet not implemented")
}
func (UnimplementedMdmServiceServer) DeleteCodeSet(context.Context, *DeleteCodeSetRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCodeSet not implemented")
}
func (UnimplementedMdmServiceServer) ListCodeItems(context.Context, *ListCodeItemsRequest) (*ListCodeItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCodeItems not implemented")
}
func (UnimplementedMdmServiceServer) GetCodeItem(context.Context, *GetCodeItemRequest) (*CodeItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCodeItem not implemented")
}
func (UnimplementedMdmServiceServer) CreateCodeItem(context.Context, *CreateCodeItemRequest) (*CodeItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCodeItem not implemented")
}
func (UnimplementedMdmServiceServer) UpdateCodeItem(context.Context, *UpdateCodeItemRequest) (*CodeItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCodeItem not implemented")
}
func (UnimplementedMdmServiceServer) DeleteCodeItem(context.Context, *DeleteCodeItemRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCodeItem not implemented")
}
func (UnimplementedMdmServiceServer) ListSystemParameters(context.Context, *ListSystemParametersRequest) (*ListSystemParametersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSystemParameters not implemented")
}
func (UnimplementedMdmServiceServer) GetSystemParameter(context.Context, *GetSystemParameterRequest) (*SystemParameter, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemParameter not implemented")
}
func (UnimplementedMdmServiceServer) CreateSystemParameter(context.Context, *CreateSystemParameterRequest) (*SystemParameter, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSystemParameter not implemented")
}
func (UnimplementedMdmServiceServer) UpdateSystemParameter(context.Context, *UpdateSystemParameterRequest) (*SystemParameter, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSystemParameter not implemented")
}
func (UnimplementedMdmServiceServer) DeleteSystemParameter(context.Context, *DeleteSystemParameterRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSystemParameter not implemented")
}
func (UnimplementedMdmServiceServer) ListCreditInstitutions(context.Context, *ListCreditInstitutionsRequest) (*ListCreditInstitutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCreditInstitutions not implemented")
}
func (UnimplementedMdmServiceServer) GetCreditInstitution(context.Context, *GetCreditInstitutionRequest) (*CreditInstitution, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCreditInstitution not implemented")
}
func (UnimplementedMdmServiceServer) CreateCreditInstitution(context.Context, *CreateCreditInstitutionRequest) (*CreditInstitution, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCreditInstitution not implemented")
}
func (UnimplementedMdmServiceServer) UpdateCreditInstitution(context.Context, *UpdateCreditInstitutionRequest) (*CreditInstitution, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCreditInstitution not implemented")
}
func (UnimplementedMdmServiceServer) DeleteCreditInstitution(context.Context, *DeleteCreditInstitutionRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCreditInstitution not implemented")
}
func (UnimplementedMdmServiceServer) mustEmbedUnimplementedMdmServiceServer() {}
func (UnimplementedMdmServiceServer) testEmbeddedByValue()                    {}

// UnsafeMdmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MdmServiceServer will
// result in compilation errors.
type UnsafeMdmServiceServer interface {
	mustEmbedUnimplementedMdmServiceServer()
}

func RegisterMdmServiceServer(s grpc.ServiceRegistrar, srv MdmServiceServer) {
	// If the following call panics, it indicates UnimplementedMdmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MdmService_ServiceDesc, srv)
}

func _MdmService_ListAdministrativeUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdministrativeUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListAdministrativeUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListAdministrativeUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListAdministrativeUnits(ctx, req.(*ListAdministrativeUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListAdministrativeUnitTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdministrativeUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListAdministrativeUnitTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListAdministrativeUnitTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListAdministrativeUnitTree(ctx, req.(*ListAdministrativeUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListProvinces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdministrativeUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListProvinces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListProvinces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListProvinces(ctx, req.(*ListAdministrativeUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListWards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListWards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListWards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListWards(ctx, req.(*ListWardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_GetAdministrativeUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdministrativeUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetAdministrativeUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_GetAdministrativeUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetAdministrativeUnit(ctx, req.(*GetAdministrativeUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_CreateAdministrativeUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdministrativeUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).CreateAdministrativeUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_CreateAdministrativeUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).CreateAdministrativeUnit(ctx, req.(*CreateAdministrativeUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_UpdateAdministrativeUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdministrativeUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).UpdateAdministrativeUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_UpdateAdministrativeUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).UpdateAdministrativeUnit(ctx, req.(*UpdateAdministrativeUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_DeleteAdministrativeUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdministrativeUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).DeleteAdministrativeUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_DeleteAdministrativeUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).DeleteAdministrativeUnit(ctx, req.(*DeleteAdministrativeUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_SyncAdministrativeUnitsFromAddressKit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncAdministrativeUnitsFromAddressKitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).SyncAdministrativeUnitsFromAddressKit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_SyncAdministrativeUnitsFromAddressKit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).SyncAdministrativeUnitsFromAddressKit(ctx, req.(*SyncAdministrativeUnitsFromAddressKitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListAreaTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreaTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListAreaTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListAreaTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListAreaTypes(ctx, req.(*ListAreaTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_GetAreaType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAreaTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetAreaType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_GetAreaType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetAreaType(ctx, req.(*GetAreaTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_CreateAreaType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAreaTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).CreateAreaType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_CreateAreaType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).CreateAreaType(ctx, req.(*CreateAreaTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_UpdateAreaType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAreaTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).UpdateAreaType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_UpdateAreaType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).UpdateAreaType(ctx, req.(*UpdateAreaTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_DeleteAreaType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAreaTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).DeleteAreaType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_DeleteAreaType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).DeleteAreaType(ctx, req.(*DeleteAreaTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListAreas(ctx, req.(*ListAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListAreaTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListAreaTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListAreaTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListAreaTree(ctx, req.(*ListAreasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_GetArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_GetArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetArea(ctx, req.(*GetAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_CreateArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).CreateArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_CreateArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).CreateArea(ctx, req.(*CreateAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_UpdateArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).UpdateArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_UpdateArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).UpdateArea(ctx, req.(*UpdateAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_DeleteArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).DeleteArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_DeleteArea_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).DeleteArea(ctx, req.(*DeleteAreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_AssignAreaAdministrativeUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignAreaAdministrativeUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).AssignAreaAdministrativeUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_AssignAreaAdministrativeUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).AssignAreaAdministrativeUnit(ctx, req.(*AssignAreaAdministrativeUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListAreaAdministrativeUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAreaAdministrativeUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListAreaAdministrativeUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListAreaAdministrativeUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListAreaAdministrativeUnits(ctx, req.(*ListAreaAdministrativeUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_RemoveAreaAdministrativeUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAreaAdministrativeUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).RemoveAreaAdministrativeUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_RemoveAreaAdministrativeUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).RemoveAreaAdministrativeUnit(ctx, req.(*RemoveAreaAdministrativeUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListCodeSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCodeSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListCodeSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListCodeSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListCodeSets(ctx, req.(*ListCodeSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_GetCodeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetCodeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_GetCodeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetCodeSet(ctx, req.(*GetCodeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_CreateCodeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCodeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).CreateCodeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_CreateCodeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).CreateCodeSet(ctx, req.(*CreateCodeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_UpdateCodeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCodeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).UpdateCodeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_UpdateCodeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).UpdateCodeSet(ctx, req.(*UpdateCodeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_DeleteCodeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCodeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).DeleteCodeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_DeleteCodeSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).DeleteCodeSet(ctx, req.(*DeleteCodeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListCodeItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCodeItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListCodeItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListCodeItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListCodeItems(ctx, req.(*ListCodeItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_GetCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodeItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_GetCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetCodeItem(ctx, req.(*GetCodeItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_CreateCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCodeItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).CreateCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_CreateCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).CreateCodeItem(ctx, req.(*CreateCodeItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_UpdateCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCodeItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).UpdateCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_UpdateCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).UpdateCodeItem(ctx, req.(*UpdateCodeItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_DeleteCodeItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCodeItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).DeleteCodeItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_DeleteCodeItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).DeleteCodeItem(ctx, req.(*DeleteCodeItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListSystemParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSystemParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListSystemParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListSystemParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListSystemParameters(ctx, req.(*ListSystemParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_GetSystemParameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetSystemParameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_GetSystemParameter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetSystemParameter(ctx, req.(*GetSystemParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_CreateSystemParameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSystemParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).CreateSystemParameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_CreateSystemParameter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).CreateSystemParameter(ctx, req.(*CreateSystemParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_UpdateSystemParameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSystemParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).UpdateSystemParameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_UpdateSystemParameter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).UpdateSystemParameter(ctx, req.(*UpdateSystemParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_DeleteSystemParameter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSystemParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).DeleteSystemParameter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_DeleteSystemParameter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).DeleteSystemParameter(ctx, req.(*DeleteSystemParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_ListCreditInstitutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCreditInstitutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).ListCreditInstitutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_ListCreditInstitutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).ListCreditInstitutions(ctx, req.(*ListCreditInstitutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_GetCreditInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreditInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).GetCreditInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_GetCreditInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).GetCreditInstitution(ctx, req.(*GetCreditInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_CreateCreditInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCreditInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).CreateCreditInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_CreateCreditInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).CreateCreditInstitution(ctx, req.(*CreateCreditInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_UpdateCreditInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCreditInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).UpdateCreditInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_UpdateCreditInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).UpdateCreditInstitution(ctx, req.(*UpdateCreditInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MdmService_DeleteCreditInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCreditInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MdmServiceServer).DeleteCreditInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MdmService_DeleteCreditInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MdmServiceServer).DeleteCreditInstitution(ctx, req.(*DeleteCreditInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MdmService_ServiceDesc is the grpc.ServiceDesc for MdmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MdmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mdm.v1.MdmService",
	HandlerType: (*MdmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAdministrativeUnits",
			Handler:    _MdmService_ListAdministrativeUnits_Handler,
		},
		{
			MethodName: "ListAdministrativeUnitTree",
			Handler:    _MdmService_ListAdministrativeUnitTree_Handler,
		},
		{
			MethodName: "ListProvinces",
			Handler:    _MdmService_ListProvinces_Handler,
		},
		{
			MethodName: "ListWards",
			Handler:    _MdmService_ListWards_Handler,
		},
		{
			MethodName: "GetAdministrativeUnit",
			Handler:    _MdmService_GetAdministrativeUnit_Handler,
		},
		{
			MethodName: "CreateAdministrativeUnit",
			Handler:    _MdmService_CreateAdministrativeUnit_Handler,
		},
		{
			MethodName: "UpdateAdministrativeUnit",
			Handler:    _MdmService_UpdateAdministrativeUnit_Handler,
		},
		{
			MethodName: "DeleteAdministrativeUnit",
			Handler:    _MdmService_DeleteAdministrativeUnit_Handler,
		},
		{
			MethodName: "SyncAdministrativeUnitsFromAddressKit",
			Handler:    _MdmService_SyncAdministrativeUnitsFromAddressKit_Handler,
		},
		{
			MethodName: "ListAreaTypes",
			Handler:    _MdmService_ListAreaTypes_Handler,
		},
		{
			MethodName: "GetAreaType",
			Handler:    _MdmService_GetAreaType_Handler,
		},
		{
			MethodName: "CreateAreaType",
			Handler:    _MdmService_CreateAreaType_Handler,
		},
		{
			MethodName: "UpdateAreaType",
			Handler:    _MdmService_UpdateAreaType_Handler,
		},
		{
			MethodName: "DeleteAreaType",
			Handler:    _MdmService_DeleteAreaType_Handler,
		},
		{
			MethodName: "ListAreas",
			Handler:    _MdmService_ListAreas_Handler,
		},
		{
			MethodName: "ListAreaTree",
			Handler:    _MdmService_ListAreaTree_Handler,
		},
		{
			MethodName: "GetArea",
			Handler:    _MdmService_GetArea_Handler,
		},
		{
			MethodName: "CreateArea",
			Handler:    _MdmService_CreateArea_Handler,
		},
		{
			MethodName: "UpdateArea",
			Handler:    _MdmService_UpdateArea_Handler,
		},
		{
			MethodName: "DeleteArea",
			Handler:    _MdmService_DeleteArea_Handler,
		},
		{
			MethodName: "AssignAreaAdministrativeUnit",
			Handler:    _MdmService_AssignAreaAdministrativeUnit_Handler,
		},
		{
			MethodName: "ListAreaAdministrativeUnits",
			Handler:    _MdmService_ListAreaAdministrativeUnits_Handler,
		},
		{
			MethodName: "RemoveAreaAdministrativeUnit",
			Handler:    _MdmService_RemoveAreaAdministrativeUnit_Handler,
		},
		{
			MethodName: "ListCodeSets",
			Handler:    _MdmService_ListCodeSets_Handler,
		},
		{
			MethodName: "GetCodeSet",
			Handler:    _MdmService_GetCodeSet_Handler,
		},
		{
			MethodName: "CreateCodeSet",
			Handler:    _MdmService_CreateCodeSet_Handler,
		},
		{
			MethodName: "UpdateCodeSet",
			Handler:    _MdmService_UpdateCodeSet_Handler,
		},
		{
			MethodName: "DeleteCodeSet",
			Handler:    _MdmService_DeleteCodeSet_Handler,
		},
		{
			MethodName: "ListCodeItems",
			Handler:    _MdmService_ListCodeItems_Handler,
		},
		{
			MethodName: "GetCodeItem",
			Handler:    _MdmService_GetCodeItem_Handler,
		},
		{
			MethodName: "CreateCodeItem",
			Handler:    _MdmService_CreateCodeItem_Handler,
		},
		{
			MethodName: "UpdateCodeItem",
			Handler:    _MdmService_UpdateCodeItem_Handler,
		},
		{
			MethodName: "DeleteCodeItem",
			Handler:    _MdmService_DeleteCodeItem_Handler,
		},
		{
			MethodName: "ListSystemParameters",
			Handler:    _MdmService_ListSystemParameters_Handler,
		},
		{
			MethodName: "GetSystemParameter",
			Handler:    _MdmService_GetSystemParameter_Handler,
		},
		{
			MethodName: "CreateSystemParameter",
			Handler:    _MdmService_CreateSystemParameter_Handler,
		},
		{
			MethodName: "UpdateSystemParameter",
			Handler:    _MdmService_UpdateSystemParameter_Handler,
		},
		{
			MethodName: "DeleteSystemParameter",
			Handler:    _MdmService_DeleteSystemParameter_Handler,
		},
		{
			MethodName: "ListCreditInstitutions",
			Handler:    _MdmService_ListCreditInstitutions_Handler,
		},
		{
			MethodName: "GetCreditInstitution",
			Handler:    _MdmService_GetCreditInstitution_Handler,
		},
		{
			MethodName: "CreateCreditInstitution",
			Handler:    _MdmService_CreateCreditInstitution_Handler,
		},
		{
			MethodName: "UpdateCreditInstitution",
			Handler:    _MdmService_UpdateCreditInstitution_Handler,
		},
		{
			MethodName: "DeleteCreditInstitution",
			Handler:    _MdmService_DeleteCreditInstitution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mdm/v1/mdm.proto",
}
