spring:
  application:
    name: crm-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://thinkcenter:5432/crm?options=-c%20timezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:crm}
    password: ${SPRING_DATASOURCE_PASSWORD:crm@123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:thinkcenter:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

zeebe:
  client:
    broker:
      gateway-address: ${ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS:thinkcenter:26500}
    security:
      plaintext: ${ZEEBE_CLIENT_SECURITY_PLAINTEXT:true}

server:
  port: 8010

grpc:
  server:
    port: 9010
