// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/arda-labs/arda/arda-be-go/services/iam-service/internal/biz"
	"github.com/arda-labs/arda/arda-be-go/services/iam-service/internal/conf"
	"github.com/arda-labs/arda/arda-be-go/services/iam-service/internal/data"
	"github.com/arda-labs/arda/arda-be-go/services/iam-service/internal/server"
	"github.com/arda-labs/arda/arda-be-go/services/iam-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, zitadel *conf.Zitadel, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	roleRepo := data.NewRoleRepo(dataData)
	permissionRepo := data.NewPermissionRepo(dataData)
	permissionCache := data.NewPermissionCache(dataData)
	auditRepo := data.NewAuditRepo(dataData)
	auditUsecase := biz.NewAuditUsecase(auditRepo)
	permissionUsecase := biz.NewPermissionUsecase(roleRepo, permissionRepo, permissionCache, auditUsecase)
	authUsecase := biz.NewAuthUsecase(zitadel, jwt, permissionUsecase, logger)
	membershipRepo := data.NewMembershipRepo(dataData)
	membershipUsecase := biz.NewMembershipUsecase(membershipRepo)
	userUsecase := biz.NewUserUsecase(userRepo, authUsecase, membershipUsecase)
	tenantRepo := data.NewTenantRepo(dataData)
	tenantUsecase := biz.NewTenantUsecase(tenantRepo, membershipUsecase)
	roleUsecase := biz.NewRoleUsecase(roleRepo, auditUsecase, permissionCache)
	groupRepo := data.NewGroupRepo(dataData, logger)
	groupUsecase := biz.NewGroupUsecase(groupRepo, permissionCache, auditUsecase)
	iamService := service.NewIAMService(userUsecase, tenantUsecase, membershipUsecase, roleUsecase, permissionUsecase, authUsecase, auditUsecase, groupUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, iamService, logger)
	menuRepo := data.NewMenuRepo(dataData, logger)
	menuUsecase := biz.NewMenuUsecase(menuRepo, permissionUsecase, logger)
	menuService := service.NewMenuService(menuUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, iamService, menuService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
