// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/iam/v1/menu.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Menu messages
type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Route         string                 `protobuf:"bytes,7,opt,name=route,proto3" json:"route,omitempty"`
	SortOrder     int32                  `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Menu) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Menu) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Menu) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Menu) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Menu) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *Menu) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Menu) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Menu) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Menu) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Requests
type GetMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuRequest) Reset() {
	*x = GetMenuRequest{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuRequest) ProtoMessage() {}

func (x *GetMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuRequest.ProtoReflect.Descriptor instead.
func (*GetMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{1}
}

type GetMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuResponse) Reset() {
	*x = GetMenuResponse{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuResponse) ProtoMessage() {}

func (x *GetMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuResponse.ProtoReflect.Descriptor instead.
func (*GetMenuResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{2}
}

func (x *GetMenuResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Route         string                 `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Children      []*MenuItem            `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{3}
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuItem) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *MenuItem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *MenuItem) GetChildren() []*MenuItem {
	if x != nil {
		return x.Children
	}
	return nil
}

type ListMenusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenusRequest) Reset() {
	*x = ListMenusRequest{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenusRequest) ProtoMessage() {}

func (x *ListMenusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenusRequest.ProtoReflect.Descriptor instead.
func (*ListMenusRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{4}
}

func (x *ListMenusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListMenusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*Menu                `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenusResponse) Reset() {
	*x = ListMenusResponse{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenusResponse) ProtoMessage() {}

func (x *ListMenusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenusResponse.ProtoReflect.Descriptor instead.
func (*ListMenusResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{5}
}

func (x *ListMenusResponse) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type CreateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Route         string                 `protobuf:"bytes,6,opt,name=route,proto3" json:"route,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuRequest) Reset() {
	*x = CreateMenuRequest{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuRequest) ProtoMessage() {}

func (x *CreateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMenuRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateMenuRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateMenuRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateMenuRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *CreateMenuRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateMenuRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type UpdateMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Route         string                 `protobuf:"bytes,6,opt,name=route,proto3" json:"route,omitempty"`
	SortOrder     int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuRequest) Reset() {
	*x = UpdateMenuRequest{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuRequest) ProtoMessage() {}

func (x *UpdateMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMenuRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMenuRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpdateMenuRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpdateMenuRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateMenuRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *UpdateMenuRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *UpdateMenuRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type DeleteMenuRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuRequest) Reset() {
	*x = DeleteMenuRequest{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuRequest) ProtoMessage() {}

func (x *DeleteMenuRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuRequest) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMenuRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuResponse) Reset() {
	*x = DeleteMenuResponse{}
	mi := &file_api_iam_v1_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuResponse) ProtoMessage() {}

func (x *DeleteMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_iam_v1_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuResponse.ProtoReflect.Descriptor instead.
func (*DeleteMenuResponse) Descriptor() ([]byte, []int) {
	return file_api_iam_v1_menu_proto_rawDescGZIP(), []int{9}
}

var File_api_iam_v1_menu_proto protoreflect.FileDescriptor

const file_api_iam_v1_menu_proto_rawDesc = "" +
	"\n" +
	"\x15api/iam/v1/menu.proto\x12\x06iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x02\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x14\n" +
	"\x05route\x18\a \x01(\tR\x05route\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\x05R\tsortOrder\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x10\n" +
	"\x0eGetMenuRequest\"9\n" +
	"\x0fGetMenuResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.iam.v1.MenuItemR\x05items\"\xa5\x01\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05route\x18\x04 \x01(\tR\x05route\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x12,\n" +
	"\bchildren\x18\x06 \x03(\v2\x10.iam.v1.MenuItemR\bchildren\"/\n" +
	"\x10ListMenusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"7\n" +
	"\x11ListMenusResponse\x12\"\n" +
	"\x05menus\x18\x01 \x03(\v2\f.iam.v1.MenuR\x05menus\"\xd8\x01\n" +
	"\x11CreateMenuRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05route\x18\x06 \x01(\tR\x05route\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"\xcb\x01\n" +
	"\x11UpdateMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x14\n" +
	"\x05route\x18\x06 \x01(\tR\x05route\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"#\n" +
	"\x11DeleteMenuRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteMenuResponse2\xaf\x03\n" +
	"\vMenuService\x12O\n" +
	"\aGetMenu\x12\x16.iam.v1.GetMenuRequest\x1a\x17.iam.v1.GetMenuResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/me/menu\x12S\n" +
	"\tListMenus\x12\x18.iam.v1.ListMenusRequest\x1a\x19.iam.v1.ListMenusResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/menus\x12K\n" +
	"\n" +
	"CreateMenu\x12\x19.iam.v1.CreateMenuRequest\x1a\f.iam.v1.Menu\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/menus\x12P\n" +
	"\n" +
	"UpdateMenu\x12\x19.iam.v1.UpdateMenuRequest\x1a\f.iam.v1.Menu\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/menus/{id}\x12[\n" +
	"\n" +
	"DeleteMenu\x12\x19.iam.v1.DeleteMenuRequest\x1a\x1a.iam.v1.DeleteMenuResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/menus/{id}BIZGgithub.com/arda-labs/arda/arda-be-go/services/iam-service/api/iam/v1;v1b\x06proto3"

var (
	file_api_iam_v1_menu_proto_rawDescOnce sync.Once
	file_api_iam_v1_menu_proto_rawDescData []byte
)

func file_api_iam_v1_menu_proto_rawDescGZIP() []byte {
	file_api_iam_v1_menu_proto_rawDescOnce.Do(func() {
		file_api_iam_v1_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_iam_v1_menu_proto_rawDesc), len(file_api_iam_v1_menu_proto_rawDesc)))
	})
	return file_api_iam_v1_menu_proto_rawDescData
}

var file_api_iam_v1_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_iam_v1_menu_proto_goTypes = []any{
	(*Menu)(nil),                  // 0: iam.v1.Menu
	(*GetMenuRequest)(nil),        // 1: iam.v1.GetMenuRequest
	(*GetMenuResponse)(nil),       // 2: iam.v1.GetMenuResponse
	(*MenuItem)(nil),              // 3: iam.v1.MenuItem
	(*ListMenusRequest)(nil),      // 4: iam.v1.ListMenusRequest
	(*ListMenusResponse)(nil),     // 5: iam.v1.ListMenusResponse
	(*CreateMenuRequest)(nil),     // 6: iam.v1.CreateMenuRequest
	(*UpdateMenuRequest)(nil),     // 7: iam.v1.UpdateMenuRequest
	(*DeleteMenuRequest)(nil),     // 8: iam.v1.DeleteMenuRequest
	(*DeleteMenuResponse)(nil),    // 9: iam.v1.DeleteMenuResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_api_iam_v1_menu_proto_depIdxs = []int32{
	10, // 0: iam.v1.Menu.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: iam.v1.Menu.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 2: iam.v1.GetMenuResponse.items:type_name -> iam.v1.MenuItem
	3,  // 3: iam.v1.MenuItem.children:type_name -> iam.v1.MenuItem
	0,  // 4: iam.v1.ListMenusResponse.menus:type_name -> iam.v1.Menu
	1,  // 5: iam.v1.MenuService.GetMenu:input_type -> iam.v1.GetMenuRequest
	4,  // 6: iam.v1.MenuService.ListMenus:input_type -> iam.v1.ListMenusRequest
	6,  // 7: iam.v1.MenuService.CreateMenu:input_type -> iam.v1.CreateMenuRequest
	7,  // 8: iam.v1.MenuService.UpdateMenu:input_type -> iam.v1.UpdateMenuRequest
	8,  // 9: iam.v1.MenuService.DeleteMenu:input_type -> iam.v1.DeleteMenuRequest
	2,  // 10: iam.v1.MenuService.GetMenu:output_type -> iam.v1.GetMenuResponse
	5,  // 11: iam.v1.MenuService.ListMenus:output_type -> iam.v1.ListMenusResponse
	0,  // 12: iam.v1.MenuService.CreateMenu:output_type -> iam.v1.Menu
	0,  // 13: iam.v1.MenuService.UpdateMenu:output_type -> iam.v1.Menu
	9,  // 14: iam.v1.MenuService.DeleteMenu:output_type -> iam.v1.DeleteMenuResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_iam_v1_menu_proto_init() }
func file_api_iam_v1_menu_proto_init() {
	if File_api_iam_v1_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_iam_v1_menu_proto_rawDesc), len(file_api_iam_v1_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_iam_v1_menu_proto_goTypes,
		DependencyIndexes: file_api_iam_v1_menu_proto_depIdxs,
		MessageInfos:      file_api_iam_v1_menu_proto_msgTypes,
	}.Build()
	File_api_iam_v1_menu_proto = out.File
	file_api_iam_v1_menu_proto_goTypes = nil
	file_api_iam_v1_menu_proto_depIdxs = nil
}
