// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: api/iam/v1/iam.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIAMServiceApprovePermission = "/iam.v1.IAMService/ApprovePermission"
const OperationIAMServiceAssignRole = "/iam.v1.IAMService/AssignRole"
const OperationIAMServiceCheckPermission = "/iam.v1.IAMService/CheckPermission"
const OperationIAMServiceCreateRole = "/iam.v1.IAMService/CreateRole"
const OperationIAMServiceCreateTenant = "/iam.v1.IAMService/CreateTenant"
const OperationIAMServiceCustomLogin = "/iam.v1.IAMService/CustomLogin"
const OperationIAMServiceDeleteRole = "/iam.v1.IAMService/DeleteRole"
const OperationIAMServiceDeleteTenant = "/iam.v1.IAMService/DeleteTenant"
const OperationIAMServiceForwardAuth = "/iam.v1.IAMService/ForwardAuth"
const OperationIAMServiceGetCurrentUser = "/iam.v1.IAMService/GetCurrentUser"
const OperationIAMServiceGetCurrentUserPermissions = "/iam.v1.IAMService/GetCurrentUserPermissions"
const OperationIAMServiceGetRole = "/iam.v1.IAMService/GetRole"
const OperationIAMServiceGetTenant = "/iam.v1.IAMService/GetTenant"
const OperationIAMServiceGetUser = "/iam.v1.IAMService/GetUser"
const OperationIAMServiceGetUserMemberships = "/iam.v1.IAMService/GetUserMemberships"
const OperationIAMServiceGrantResourcePermission = "/iam.v1.IAMService/GrantResourcePermission"
const OperationIAMServiceInviteMember = "/iam.v1.IAMService/InviteMember"
const OperationIAMServiceListMembers = "/iam.v1.IAMService/ListMembers"
const OperationIAMServiceListPendingApprovals = "/iam.v1.IAMService/ListPendingApprovals"
const OperationIAMServiceListPermissions = "/iam.v1.IAMService/ListPermissions"
const OperationIAMServiceListRoles = "/iam.v1.IAMService/ListRoles"
const OperationIAMServiceListUsers = "/iam.v1.IAMService/ListUsers"
const OperationIAMServiceRejectPermission = "/iam.v1.IAMService/RejectPermission"
const OperationIAMServiceRemoveMember = "/iam.v1.IAMService/RemoveMember"
const OperationIAMServiceRevokeResourcePermission = "/iam.v1.IAMService/RevokeResourcePermission"
const OperationIAMServiceRevokeRole = "/iam.v1.IAMService/RevokeRole"
const OperationIAMServiceUpdateRole = "/iam.v1.IAMService/UpdateRole"
const OperationIAMServiceUpdateTenant = "/iam.v1.IAMService/UpdateTenant"

type IAMServiceHTTPServer interface {
	ApprovePermission(context.Context, *ApprovePermissionRequest) (*ResourcePermission, error)
	AssignRole(context.Context, *AssignRoleRequest) (*UserRole, error)
	// CheckPermission Permissions
	CheckPermission(context.Context, *CheckPermissionRequest) (*CheckPermissionResponse, error)
	// CreateRole Roles
	CreateRole(context.Context, *CreateRoleRequest) (*Role, error)
	// CreateTenant Tenants
	CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error)
	// CustomLogin Auth
	CustomLogin(context.Context, *CustomLoginRequest) (*CustomLoginReply, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error)
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
	// ForwardAuth Forward Auth (Dành cho APISIX)
	ForwardAuth(context.Context, *ForwardAuthRequest) (*ForwardAuthResponse, error)
	// GetCurrentUser Users
	GetCurrentUser(context.Context, *GetCurrentUserRequest) (*GetCurrentUserResponse, error)
	GetCurrentUserPermissions(context.Context, *GetCurrentUserPermissionsRequest) (*ListPermissionsResponse, error)
	GetRole(context.Context, *GetRoleRequest) (*Role, error)
	GetTenant(context.Context, *GetTenantRequest) (*Tenant, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	GetUserMemberships(context.Context, *GetUserMembershipsRequest) (*GetUserMembershipsResponse, error)
	GrantResourcePermission(context.Context, *GrantResourcePermissionRequest) (*ResourcePermission, error)
	// InviteMember Membership
	InviteMember(context.Context, *InviteMemberRequest) (*Membership, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	// ListPendingApprovals Approvals (Maker-Checker)
	ListPendingApprovals(context.Context, *ListPendingApprovalsRequest) (*ListPendingApprovalsResponse, error)
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	RejectPermission(context.Context, *RejectPermissionRequest) (*ResourcePermission, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*RemoveMemberResponse, error)
	RevokeResourcePermission(context.Context, *RevokeResourcePermissionRequest) (*RevokeResourcePermissionResponse, error)
	RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error)
	UpdateRole(context.Context, *UpdateRoleRequest) (*Role, error)
	UpdateTenant(context.Context, *UpdateTenantRequest) (*Tenant, error)
}

func RegisterIAMServiceHTTPServer(s *http.Server, srv IAMServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/auth/login", _IAMService_CustomLogin0_HTTP_Handler(srv))
	r.GET("/v1/me", _IAMService_GetCurrentUser0_HTTP_Handler(srv))
	r.GET("/v1/users/{id}", _IAMService_GetUser0_HTTP_Handler(srv))
	r.GET("/v1/users", _IAMService_ListUsers0_HTTP_Handler(srv))
	r.POST("/v1/tenants", _IAMService_CreateTenant0_HTTP_Handler(srv))
	r.GET("/v1/tenants/{id}", _IAMService_GetTenant0_HTTP_Handler(srv))
	r.PUT("/v1/tenants/{id}", _IAMService_UpdateTenant0_HTTP_Handler(srv))
	r.DELETE("/v1/tenants/{id}", _IAMService_DeleteTenant0_HTTP_Handler(srv))
	r.GET("/v1/me/tenants", _IAMService_GetUserMemberships0_HTTP_Handler(srv))
	r.POST("/v1/tenants/{tenant_id}/invite", _IAMService_InviteMember0_HTTP_Handler(srv))
	r.GET("/v1/tenants/{tenant_id}/members", _IAMService_ListMembers0_HTTP_Handler(srv))
	r.DELETE("/v1/tenants/{tenant_id}/members/{user_id}", _IAMService_RemoveMember0_HTTP_Handler(srv))
	r.POST("/v1/roles", _IAMService_CreateRole0_HTTP_Handler(srv))
	r.GET("/v1/roles/{id}", _IAMService_GetRole0_HTTP_Handler(srv))
	r.GET("/v1/roles", _IAMService_ListRoles0_HTTP_Handler(srv))
	r.PUT("/v1/roles/{id}", _IAMService_UpdateRole0_HTTP_Handler(srv))
	r.DELETE("/v1/roles/{id}", _IAMService_DeleteRole0_HTTP_Handler(srv))
	r.POST("/v1/assign-role", _IAMService_AssignRole0_HTTP_Handler(srv))
	r.POST("/v1/revoke-role", _IAMService_RevokeRole0_HTTP_Handler(srv))
	r.GET("/v1/permissions/check", _IAMService_CheckPermission0_HTTP_Handler(srv))
	r.GET("/v1/me/permissions", _IAMService_GetCurrentUserPermissions0_HTTP_Handler(srv))
	r.POST("/v1/auth/forward", _IAMService_ForwardAuth0_HTTP_Handler(srv))
	r.GET("/v1/permissions", _IAMService_ListPermissions0_HTTP_Handler(srv))
	r.POST("/v1/resource-permissions", _IAMService_GrantResourcePermission0_HTTP_Handler(srv))
	r.DELETE("/v1/resource-permissions/{id}", _IAMService_RevokeResourcePermission0_HTTP_Handler(srv))
	r.GET("/v1/approvals/pending", _IAMService_ListPendingApprovals0_HTTP_Handler(srv))
	r.POST("/v1/approvals/{id}/approve", _IAMService_ApprovePermission0_HTTP_Handler(srv))
	r.POST("/v1/approvals/{id}/reject", _IAMService_RejectPermission0_HTTP_Handler(srv))
}

func _IAMService_CustomLogin0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CustomLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceCustomLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CustomLogin(ctx, req.(*CustomLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CustomLoginReply)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetCurrentUser0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetCurrentUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentUser(ctx, req.(*GetCurrentUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCurrentUserResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetUser0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUser(ctx, req.(*GetUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListUsers0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListUsersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListUsers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUsers(ctx, req.(*ListUsersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUsersResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_CreateTenant0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceCreateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTenant(ctx, req.(*CreateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetTenant0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTenantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTenant(ctx, req.(*GetTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _IAMService_UpdateTenant0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTenantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceUpdateTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTenant(ctx, req.(*UpdateTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Tenant)
		return ctx.Result(200, reply)
	}
}

func _IAMService_DeleteTenant0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTenantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceDeleteTenant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTenant(ctx, req.(*DeleteTenantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTenantResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetUserMemberships0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserMembershipsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetUserMemberships)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserMemberships(ctx, req.(*GetUserMembershipsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserMembershipsResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_InviteMember0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InviteMemberRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceInviteMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InviteMember(ctx, req.(*InviteMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Membership)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListMembers0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMembersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListMembers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMembers(ctx, req.(*ListMembersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMembersResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_RemoveMember0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceRemoveMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveMember(ctx, req.(*RemoveMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveMemberResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_CreateRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceCreateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*CreateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRole(ctx, req.(*GetRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListRoles0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoles(ctx, req.(*ListRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRolesResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_UpdateRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceUpdateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRole(ctx, req.(*UpdateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _IAMService_DeleteRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceDeleteRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRole(ctx, req.(*DeleteRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteRoleResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_AssignRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceAssignRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRole(ctx, req.(*AssignRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserRole)
		return ctx.Result(200, reply)
	}
}

func _IAMService_RevokeRole0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceRevokeRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeRole(ctx, req.(*RevokeRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevokeRoleResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_CheckPermission0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckPermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceCheckPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckPermission(ctx, req.(*CheckPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckPermissionResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GetCurrentUserPermissions0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentUserPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGetCurrentUserPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentUserPermissions(ctx, req.(*GetCurrentUserPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionsResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ForwardAuth0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ForwardAuthRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceForwardAuth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ForwardAuth(ctx, req.(*ForwardAuthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ForwardAuthResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListPermissions0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPermissions(ctx, req.(*ListPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPermissionsResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_GrantResourcePermission0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GrantResourcePermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceGrantResourcePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GrantResourcePermission(ctx, req.(*GrantResourcePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResourcePermission)
		return ctx.Result(200, reply)
	}
}

func _IAMService_RevokeResourcePermission0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeResourcePermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceRevokeResourcePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeResourcePermission(ctx, req.(*RevokeResourcePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevokeResourcePermissionResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ListPendingApprovals0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPendingApprovalsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceListPendingApprovals)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPendingApprovals(ctx, req.(*ListPendingApprovalsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPendingApprovalsResponse)
		return ctx.Result(200, reply)
	}
}

func _IAMService_ApprovePermission0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApprovePermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceApprovePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApprovePermission(ctx, req.(*ApprovePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResourcePermission)
		return ctx.Result(200, reply)
	}
}

func _IAMService_RejectPermission0_HTTP_Handler(srv IAMServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RejectPermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMServiceRejectPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RejectPermission(ctx, req.(*RejectPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResourcePermission)
		return ctx.Result(200, reply)
	}
}

type IAMServiceHTTPClient interface {
	ApprovePermission(ctx context.Context, req *ApprovePermissionRequest, opts ...http.CallOption) (rsp *ResourcePermission, err error)
	AssignRole(ctx context.Context, req *AssignRoleRequest, opts ...http.CallOption) (rsp *UserRole, err error)
	// CheckPermission Permissions
	CheckPermission(ctx context.Context, req *CheckPermissionRequest, opts ...http.CallOption) (rsp *CheckPermissionResponse, err error)
	// CreateRole Roles
	CreateRole(ctx context.Context, req *CreateRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	// CreateTenant Tenants
	CreateTenant(ctx context.Context, req *CreateTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
	// CustomLogin Auth
	CustomLogin(ctx context.Context, req *CustomLoginRequest, opts ...http.CallOption) (rsp *CustomLoginReply, err error)
	DeleteRole(ctx context.Context, req *DeleteRoleRequest, opts ...http.CallOption) (rsp *DeleteRoleResponse, err error)
	DeleteTenant(ctx context.Context, req *DeleteTenantRequest, opts ...http.CallOption) (rsp *DeleteTenantResponse, err error)
	// ForwardAuth Forward Auth (Dành cho APISIX)
	ForwardAuth(ctx context.Context, req *ForwardAuthRequest, opts ...http.CallOption) (rsp *ForwardAuthResponse, err error)
	// GetCurrentUser Users
	GetCurrentUser(ctx context.Context, req *GetCurrentUserRequest, opts ...http.CallOption) (rsp *GetCurrentUserResponse, err error)
	GetCurrentUserPermissions(ctx context.Context, req *GetCurrentUserPermissionsRequest, opts ...http.CallOption) (rsp *ListPermissionsResponse, err error)
	GetRole(ctx context.Context, req *GetRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	GetTenant(ctx context.Context, req *GetTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
	GetUser(ctx context.Context, req *GetUserRequest, opts ...http.CallOption) (rsp *User, err error)
	GetUserMemberships(ctx context.Context, req *GetUserMembershipsRequest, opts ...http.CallOption) (rsp *GetUserMembershipsResponse, err error)
	GrantResourcePermission(ctx context.Context, req *GrantResourcePermissionRequest, opts ...http.CallOption) (rsp *ResourcePermission, err error)
	// InviteMember Membership
	InviteMember(ctx context.Context, req *InviteMemberRequest, opts ...http.CallOption) (rsp *Membership, err error)
	ListMembers(ctx context.Context, req *ListMembersRequest, opts ...http.CallOption) (rsp *ListMembersResponse, err error)
	// ListPendingApprovals Approvals (Maker-Checker)
	ListPendingApprovals(ctx context.Context, req *ListPendingApprovalsRequest, opts ...http.CallOption) (rsp *ListPendingApprovalsResponse, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsRequest, opts ...http.CallOption) (rsp *ListPermissionsResponse, err error)
	ListRoles(ctx context.Context, req *ListRolesRequest, opts ...http.CallOption) (rsp *ListRolesResponse, err error)
	ListUsers(ctx context.Context, req *ListUsersRequest, opts ...http.CallOption) (rsp *ListUsersResponse, err error)
	RejectPermission(ctx context.Context, req *RejectPermissionRequest, opts ...http.CallOption) (rsp *ResourcePermission, err error)
	RemoveMember(ctx context.Context, req *RemoveMemberRequest, opts ...http.CallOption) (rsp *RemoveMemberResponse, err error)
	RevokeResourcePermission(ctx context.Context, req *RevokeResourcePermissionRequest, opts ...http.CallOption) (rsp *RevokeResourcePermissionResponse, err error)
	RevokeRole(ctx context.Context, req *RevokeRoleRequest, opts ...http.CallOption) (rsp *RevokeRoleResponse, err error)
	UpdateRole(ctx context.Context, req *UpdateRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	UpdateTenant(ctx context.Context, req *UpdateTenantRequest, opts ...http.CallOption) (rsp *Tenant, err error)
}

type IAMServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewIAMServiceHTTPClient(client *http.Client) IAMServiceHTTPClient {
	return &IAMServiceHTTPClientImpl{client}
}

func (c *IAMServiceHTTPClientImpl) ApprovePermission(ctx context.Context, in *ApprovePermissionRequest, opts ...http.CallOption) (*ResourcePermission, error) {
	var out ResourcePermission
	pattern := "/v1/approvals/{id}/approve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceApprovePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...http.CallOption) (*UserRole, error) {
	var out UserRole
	pattern := "/v1/assign-role"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceAssignRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CheckPermission Permissions
func (c *IAMServiceHTTPClientImpl) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...http.CallOption) (*CheckPermissionResponse, error) {
	var out CheckPermissionResponse
	pattern := "/v1/permissions/check"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceCheckPermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateRole Roles
func (c *IAMServiceHTTPClientImpl) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceCreateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTenant Tenants
func (c *IAMServiceHTTPClientImpl) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceCreateTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CustomLogin Auth
func (c *IAMServiceHTTPClientImpl) CustomLogin(ctx context.Context, in *CustomLoginRequest, opts ...http.CallOption) (*CustomLoginReply, error) {
	var out CustomLoginReply
	pattern := "/v1/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceCustomLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...http.CallOption) (*DeleteRoleResponse, error) {
	var out DeleteRoleResponse
	pattern := "/v1/roles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceDeleteRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...http.CallOption) (*DeleteTenantResponse, error) {
	var out DeleteTenantResponse
	pattern := "/v1/tenants/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceDeleteTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ForwardAuth Forward Auth (Dành cho APISIX)
func (c *IAMServiceHTTPClientImpl) ForwardAuth(ctx context.Context, in *ForwardAuthRequest, opts ...http.CallOption) (*ForwardAuthResponse, error) {
	var out ForwardAuthResponse
	pattern := "/v1/auth/forward"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceForwardAuth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCurrentUser Users
func (c *IAMServiceHTTPClientImpl) GetCurrentUser(ctx context.Context, in *GetCurrentUserRequest, opts ...http.CallOption) (*GetCurrentUserResponse, error) {
	var out GetCurrentUserResponse
	pattern := "/v1/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetCurrentUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) GetCurrentUserPermissions(ctx context.Context, in *GetCurrentUserPermissionsRequest, opts ...http.CallOption) (*ListPermissionsResponse, error) {
	var out ListPermissionsResponse
	pattern := "/v1/me/permissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetCurrentUserPermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) GetRole(ctx context.Context, in *GetRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) GetUser(ctx context.Context, in *GetUserRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/users/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) GetUserMemberships(ctx context.Context, in *GetUserMembershipsRequest, opts ...http.CallOption) (*GetUserMembershipsResponse, error) {
	var out GetUserMembershipsResponse
	pattern := "/v1/me/tenants"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceGetUserMemberships))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) GrantResourcePermission(ctx context.Context, in *GrantResourcePermissionRequest, opts ...http.CallOption) (*ResourcePermission, error) {
	var out ResourcePermission
	pattern := "/v1/resource-permissions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceGrantResourcePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// InviteMember Membership
func (c *IAMServiceHTTPClientImpl) InviteMember(ctx context.Context, in *InviteMemberRequest, opts ...http.CallOption) (*Membership, error) {
	var out Membership
	pattern := "/v1/tenants/{tenant_id}/invite"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceInviteMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...http.CallOption) (*ListMembersResponse, error) {
	var out ListMembersResponse
	pattern := "/v1/tenants/{tenant_id}/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListMembers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPendingApprovals Approvals (Maker-Checker)
func (c *IAMServiceHTTPClientImpl) ListPendingApprovals(ctx context.Context, in *ListPendingApprovalsRequest, opts ...http.CallOption) (*ListPendingApprovalsResponse, error) {
	var out ListPendingApprovalsResponse
	pattern := "/v1/approvals/pending"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListPendingApprovals))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...http.CallOption) (*ListPermissionsResponse, error) {
	var out ListPermissionsResponse
	pattern := "/v1/permissions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListPermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...http.CallOption) (*ListRolesResponse, error) {
	var out ListRolesResponse
	pattern := "/v1/roles"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...http.CallOption) (*ListUsersResponse, error) {
	var out ListUsersResponse
	pattern := "/v1/users"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceListUsers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) RejectPermission(ctx context.Context, in *RejectPermissionRequest, opts ...http.CallOption) (*ResourcePermission, error) {
	var out ResourcePermission
	pattern := "/v1/approvals/{id}/reject"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceRejectPermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...http.CallOption) (*RemoveMemberResponse, error) {
	var out RemoveMemberResponse
	pattern := "/v1/tenants/{tenant_id}/members/{user_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceRemoveMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) RevokeResourcePermission(ctx context.Context, in *RevokeResourcePermissionRequest, opts ...http.CallOption) (*RevokeResourcePermissionResponse, error) {
	var out RevokeResourcePermissionResponse
	pattern := "/v1/resource-permissions/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIAMServiceRevokeResourcePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...http.CallOption) (*RevokeRoleResponse, error) {
	var out RevokeRoleResponse
	pattern := "/v1/revoke-role"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceRevokeRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceUpdateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMServiceHTTPClientImpl) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...http.CallOption) (*Tenant, error) {
	var out Tenant
	pattern := "/v1/tenants/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIAMServiceUpdateTenant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
