server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Cấm cache riêng file env.js (vì chứa cấu hình tuỳ môi trường)
    location = /env.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        expires off;
    }

    # Các file tĩnh khác vẫn cache 1 năm (Angular sinh ra file có hash name nên cache thoải mái)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    location = /module-federation.manifest.json {
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin *;
    }

    # Đảm bảo i18n không bị cache và hỗ trợ CORS nếu cần chia sẻ giữa các MFE
    location /i18n/ {
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin *;
    }

    location = /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
