/**
 * Configuration for Customer Field Names used in Audits and UI
 */
export const CUSTOMER_FIELD_NAMES = {
  basicInfo: {
    customerCode: 'Mã khách hàng',
    customerName: 'Tên khách hàng',
    customerType: 'Phân loại khách hàng',
    orgCode: 'Chi nhánh',
    provinceCode: 'Mã tỉnh/thành phố',
    wardCode: 'Mã phường/xã',
    permanentAddress: 'Địa chỉ thường trú',
    currentAddress: 'Địa chỉ hiện tại',
    areaCode: 'Mã khu vực',
    mobileNumber: 'Số di động',
    phoneNumber: 'Số cố định',
    email: 'Email',
    taxCode: 'Mã số thuế',
    fax: 'Fax',
    economicTypeCode: 'Loại hình kinh tế',
    industryCode: 'Ngành kinh tế',
    bankAccount: 'Số tài khoản',
    bankName: 'Tại ngân hàng',
  },
  identityInfoPersonal: {
    genderCode: 'Giới tính',
    dateOfBirth: 'Ngày sinh',
    placeOfBirth: 'Nơi sinh',
    ethnicityCode: 'Dân tộc',
    maritalStatus: 'Tình trạng hôn nhân',
    professionTypeCode: 'Nghề nghiệp',
    eduLevelCode: 'Trình độ học vấn',
    eduBackgroundCode: 'Chuyên ngành đào tạo',
    identificationType: 'Loại định danh',
    identificationId: 'Số định danh',
    identificationIdOld: 'Số định danh cũ',
    issueDate: 'Ngày cấp',
    expiryDate: 'Ngày hết hiệu lực',
    issuePlace: 'Nơi cấp',
  },
  identityInfoCompany: {
    corpShortName: 'Tên tắt doanh nghiệp',
    businessLicenseNo: 'Số đăng ký kinh doanh',
    businessLicenseDate: 'Ngày cấp ĐKKD',
    issuedBy: 'Cơ quan ban hành',
    establishedDate: 'Ngày thành lập',
    website: 'Website',
    legalRepName: 'Người đại diện',
    legalRepTitle: 'Chức vụ người đại diện',
    legalRepIdNo: 'Số định danh',
    industryDetail: 'Ngành kinh doanh',
  },
  extendedInfo: {
    segmentType: 'Loại khách hàng',
    segmentCode: 'Phân khúc',
    segmentRankCode: 'Hạng phân khúc',
    profession: 'Nghề nghiệp',
    jobTitle: 'Chức danh công việc',
    workTimeValue: 'Thời gian làm việc',
    workTimeUnit: 'Đơn vị thời gian',
    contractType: 'Loại hợp đồng',
    workplace: 'Nơi làm việc',
    workAddress: 'Địa chỉ nơi làm việc',
    description: 'Mô tả',
    memberCardNo: 'Số thẻ hội viên',
    memberIssueDate: 'Ngày cấp thẻ hội viên',
    memberIssuePlace: 'Nơi cấp thẻ hội viên',
  },
  relations: {
    _arrayName: 'Danh sách người có liên quan',
    relatedCustomerCode: 'Mã khách hàng liên quan',
    relatedCustomerName: 'Tên khách hàng liên quan',
    mobileNumber: 'Số điện thoại',
    identificationId: 'Số định danh',
    address: 'Địa chỉ',
    relationCode: 'Mã quan hệ',
    reciprocalRelationCode: 'Mã quan hệ đối ứng',
    relationStatus: 'Mã trạng thái quan hệ',
  },
};
