// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/crm/v1/crm.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinalizeCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeCustomerRequest) Reset() {
	*x = FinalizeCustomerRequest{}
	mi := &file_api_crm_v1_crm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeCustomerRequest) ProtoMessage() {}

func (x *FinalizeCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_crm_v1_crm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeCustomerRequest.ProtoReflect.Descriptor instead.
func (*FinalizeCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_crm_v1_crm_proto_rawDescGZIP(), []int{0}
}

func (x *FinalizeCustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FinalizeCustomerRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FinalizeCustomerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeCustomerReply) Reset() {
	*x = FinalizeCustomerReply{}
	mi := &file_api_crm_v1_crm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeCustomerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeCustomerReply) ProtoMessage() {}

func (x *FinalizeCustomerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_crm_v1_crm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeCustomerReply.ProtoReflect.Descriptor instead.
func (*FinalizeCustomerReply) Descriptor() ([]byte, []int) {
	return file_api_crm_v1_crm_proto_rawDescGZIP(), []int{1}
}

func (x *FinalizeCustomerReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinalizeCustomerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_crm_v1_crm_proto protoreflect.FileDescriptor

const file_api_crm_v1_crm_proto_rawDesc = "" +
	"\n" +
	"\x14api/crm/v1/crm.proto\x12\n" +
	"api.crm.v1\"R\n" +
	"\x17FinalizeCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"K\n" +
	"\x15FinalizeCustomerReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2a\n" +
	"\x03CRM\x12Z\n" +
	"\x10FinalizeCustomer\x12#.api.crm.v1.FinalizeCustomerRequest\x1a!.api.crm.v1.FinalizeCustomerReplyBIZGgithub.com/arda-labs/arda/arda-be-go/services/bpm-service/api/crm/v1;v1b\x06proto3"

var (
	file_api_crm_v1_crm_proto_rawDescOnce sync.Once
	file_api_crm_v1_crm_proto_rawDescData []byte
)

func file_api_crm_v1_crm_proto_rawDescGZIP() []byte {
	file_api_crm_v1_crm_proto_rawDescOnce.Do(func() {
		file_api_crm_v1_crm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_crm_v1_crm_proto_rawDesc), len(file_api_crm_v1_crm_proto_rawDesc)))
	})
	return file_api_crm_v1_crm_proto_rawDescData
}

var file_api_crm_v1_crm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_crm_v1_crm_proto_goTypes = []any{
	(*FinalizeCustomerRequest)(nil), // 0: api.crm.v1.FinalizeCustomerRequest
	(*FinalizeCustomerReply)(nil),   // 1: api.crm.v1.FinalizeCustomerReply
}
var file_api_crm_v1_crm_proto_depIdxs = []int32{
	0, // 0: api.crm.v1.CRM.FinalizeCustomer:input_type -> api.crm.v1.FinalizeCustomerRequest
	1, // 1: api.crm.v1.CRM.FinalizeCustomer:output_type -> api.crm.v1.FinalizeCustomerReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_crm_v1_crm_proto_init() }
func file_api_crm_v1_crm_proto_init() {
	if File_api_crm_v1_crm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_crm_v1_crm_proto_rawDesc), len(file_api_crm_v1_crm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_crm_v1_crm_proto_goTypes,
		DependencyIndexes: file_api_crm_v1_crm_proto_depIdxs,
		MessageInfos:      file_api_crm_v1_crm_proto_msgTypes,
	}.Build()
	File_api_crm_v1_crm_proto = out.File
	file_api_crm_v1_crm_proto_goTypes = nil
	file_api_crm_v1_crm_proto_depIdxs = nil
}
