// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: notification/v1/notification.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationTemplate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	DefaultChannel string                 `protobuf:"bytes,5,opt,name=default_channel,json=defaultChannel,proto3" json:"default_channel,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationTemplate) Reset() {
	*x = NotificationTemplate{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTemplate) ProtoMessage() {}

func (x *NotificationTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTemplate.ProtoReflect.Descriptor instead.
func (*NotificationTemplate) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationTemplate) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NotificationTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotificationTemplate) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NotificationTemplate) GetDefaultChannel() string {
	if x != nil {
		return x.DefaultChannel
	}
	return ""
}

func (x *NotificationTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NotificationTemplate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type NotificationTemplateVersion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId        string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Version           int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Channel           string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Language          string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Subject           string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Body              string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	PayloadSchemaJson string                 `protobuf:"bytes,8,opt,name=payload_schema_json,json=payloadSchemaJson,proto3" json:"payload_schema_json,omitempty"`
	ApprovalStatus    string                 `protobuf:"bytes,9,opt,name=approval_status,json=approvalStatus,proto3" json:"approval_status,omitempty"`
	ApprovedBy        string                 `protobuf:"bytes,10,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	ApprovedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	ChangeNote        string                 `protobuf:"bytes,12,opt,name=change_note,json=changeNote,proto3" json:"change_note,omitempty"`
	Status            string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationTemplateVersion) Reset() {
	*x = NotificationTemplateVersion{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTemplateVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTemplateVersion) ProtoMessage() {}

func (x *NotificationTemplateVersion) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTemplateVersion.ProtoReflect.Descriptor instead.
func (*NotificationTemplateVersion) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationTemplateVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationTemplateVersion) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *NotificationTemplateVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NotificationTemplateVersion) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *NotificationTemplateVersion) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *NotificationTemplateVersion) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationTemplateVersion) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationTemplateVersion) GetPayloadSchemaJson() string {
	if x != nil {
		return x.PayloadSchemaJson
	}
	return ""
}

func (x *NotificationTemplateVersion) GetApprovalStatus() string {
	if x != nil {
		return x.ApprovalStatus
	}
	return ""
}

func (x *NotificationTemplateVersion) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *NotificationTemplateVersion) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *NotificationTemplateVersion) GetChangeNote() string {
	if x != nil {
		return x.ChangeNote
	}
	return ""
}

func (x *NotificationTemplateVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotificationTemplateVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationTemplateVersion) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ListTemplatesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTemplatesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListTemplatesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTemplatesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Templates     []*NotificationTemplate `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	NextPageToken string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ListTemplatesResponse) GetTemplates() []*NotificationTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *GetTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *NotificationTemplate  `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTemplateRequest) GetTemplate() *NotificationTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Template      *NotificationTemplate  `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTemplateRequest) GetTemplate() *NotificationTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTemplateVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateVersionsRequest) Reset() {
	*x = ListTemplateVersionsRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateVersionsRequest) ProtoMessage() {}

func (x *ListTemplateVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListTemplateVersionsRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *ListTemplateVersionsRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ListTemplateVersionsRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ListTemplateVersionsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListTemplateVersionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListTemplateVersionsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Versions      []*NotificationTemplateVersion `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateVersionsResponse) Reset() {
	*x = ListTemplateVersionsResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateVersionsResponse) ProtoMessage() {}

func (x *ListTemplateVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListTemplateVersionsResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{10}
}

func (x *ListTemplateVersionsResponse) GetVersions() []*NotificationTemplateVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type CreateTemplateVersionRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	TemplateId    string                       `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Version       *NotificationTemplateVersion `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateVersionRequest) Reset() {
	*x = CreateTemplateVersionRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateVersionRequest) ProtoMessage() {}

func (x *CreateTemplateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateVersionRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTemplateVersionRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *CreateTemplateVersionRequest) GetVersion() *NotificationTemplateVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type ApproveTemplateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         string                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTemplateVersionRequest) Reset() {
	*x = ApproveTemplateVersionRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTemplateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTemplateVersionRequest) ProtoMessage() {}

func (x *ApproveTemplateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTemplateVersionRequest.ProtoReflect.Descriptor instead.
func (*ApproveTemplateVersionRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveTemplateVersionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApproveTemplateVersionRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ApproveTemplateVersionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x0fnotification.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x02\n" +
	"\x14NotificationTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12'\n" +
	"\x0fdefault_channel\x18\x05 \x01(\tR\x0edefaultChannel\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb2\x04\n" +
	"\x1bNotificationTemplateVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x12.\n" +
	"\x13payload_schema_json\x18\b \x01(\tR\x11payloadSchemaJson\x12'\n" +
	"\x0fapproval_status\x18\t \x01(\tR\x0eapprovalStatus\x12\x1f\n" +
	"\vapproved_by\x18\n" +
	" \x01(\tR\n" +
	"approvedBy\x12;\n" +
	"\vapproved_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"approvedAt\x12\x1f\n" +
	"\vchange_note\x18\f \x01(\tR\n" +
	"changeNote\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x10\n" +
	"\x0eDeleteResponse\"\x84\x01\n" +
	"\x14ListTemplatesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x84\x01\n" +
	"\x15ListTemplatesResponse\x12C\n" +
	"\ttemplates\x18\x01 \x03(\v2%.notification.v1.NotificationTemplateR\ttemplates\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"$\n" +
	"\x12GetTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x15CreateTemplateRequest\x12A\n" +
	"\btemplate\x18\x01 \x01(\v2%.notification.v1.NotificationTemplateR\btemplate\"j\n" +
	"\x15UpdateTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12A\n" +
	"\btemplate\x18\x02 \x01(\v2%.notification.v1.NotificationTemplateR\btemplate\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8c\x01\n" +
	"\x1bListTemplateVersionsRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"h\n" +
	"\x1cListTemplateVersionsResponse\x12H\n" +
	"\bversions\x18\x01 \x03(\v2,.notification.v1.NotificationTemplateVersionR\bversions\"\x87\x01\n" +
	"\x1cCreateTemplateVersionRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12F\n" +
	"\aversion\x18\x02 \x01(\v2,.notification.v1.NotificationTemplateVersionR\aversion\"Y\n" +
	"\x1dApproveTemplateVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\tR\x05actor\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note2\xde\t\n" +
	"\x13NotificationService\x12\x83\x01\n" +
	"\rListTemplates\x12%.notification.v1.ListTemplatesRequest\x1a&.notification.v1.ListTemplatesResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/notifications/templates\x12\x83\x01\n" +
	"\vGetTemplate\x12#.notification.v1.GetTemplateRequest\x1a%.notification.v1.NotificationTemplate\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/notifications/templates/{id}\x12\x87\x01\n" +
	"\x0eCreateTemplate\x12&.notification.v1.CreateTemplateRequest\x1a%.notification.v1.NotificationTemplate\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/notifications/templates\x12\x8c\x01\n" +
	"\x0eUpdateTemplate\x12&.notification.v1.UpdateTemplateRequest\x1a%.notification.v1.NotificationTemplate\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /v1/notifications/templates/{id}\x12\x83\x01\n" +
	"\x0eDeleteTemplate\x12&.notification.v1.DeleteTemplateRequest\x1a\x1f.notification.v1.DeleteResponse\"(\x82\xd3\xe4\x93\x02\"* /v1/notifications/templates/{id}\x12\xaf\x01\n" +
	"\x14ListTemplateVersions\x12,.notification.v1.ListTemplateVersionsRequest\x1a-.notification.v1.ListTemplateVersionsResponse\":\x82\xd3\xe4\x93\x024\x122/v1/notifications/templates/{template_id}/versions\x12\xb3\x01\n" +
	"\x15CreateTemplateVersion\x12-.notification.v1.CreateTemplateVersionRequest\x1a,.notification.v1.NotificationTemplateVersion\"=\x82\xd3\xe4\x93\x027:\x01*\"2/v1/notifications/templates/{template_id}/versions\x12\xb3\x01\n" +
	"\x16ApproveTemplateVersion\x12..notification.v1.ApproveTemplateVersionRequest\x1a,.notification.v1.NotificationTemplateVersion\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/notifications/template-versions/{id}/approveB[ZYgithub.com/arda-labs/arda/arda-be-go/services/notification-service/api/notification/v1;v1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_notification_v1_notification_proto_goTypes = []any{
	(*NotificationTemplate)(nil),          // 0: notification.v1.NotificationTemplate
	(*NotificationTemplateVersion)(nil),   // 1: notification.v1.NotificationTemplateVersion
	(*DeleteResponse)(nil),                // 2: notification.v1.DeleteResponse
	(*ListTemplatesRequest)(nil),          // 3: notification.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil),         // 4: notification.v1.ListTemplatesResponse
	(*GetTemplateRequest)(nil),            // 5: notification.v1.GetTemplateRequest
	(*CreateTemplateRequest)(nil),         // 6: notification.v1.CreateTemplateRequest
	(*UpdateTemplateRequest)(nil),         // 7: notification.v1.UpdateTemplateRequest
	(*DeleteTemplateRequest)(nil),         // 8: notification.v1.DeleteTemplateRequest
	(*ListTemplateVersionsRequest)(nil),   // 9: notification.v1.ListTemplateVersionsRequest
	(*ListTemplateVersionsResponse)(nil),  // 10: notification.v1.ListTemplateVersionsResponse
	(*CreateTemplateVersionRequest)(nil),  // 11: notification.v1.CreateTemplateVersionRequest
	(*ApproveTemplateVersionRequest)(nil), // 12: notification.v1.ApproveTemplateVersionRequest
	(*timestamppb.Timestamp)(nil),         // 13: google.protobuf.Timestamp
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	13, // 0: notification.v1.NotificationTemplate.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: notification.v1.NotificationTemplate.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: notification.v1.NotificationTemplateVersion.approved_at:type_name -> google.protobuf.Timestamp
	13, // 3: notification.v1.NotificationTemplateVersion.created_at:type_name -> google.protobuf.Timestamp
	13, // 4: notification.v1.NotificationTemplateVersion.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: notification.v1.ListTemplatesResponse.templates:type_name -> notification.v1.NotificationTemplate
	0,  // 6: notification.v1.CreateTemplateRequest.template:type_name -> notification.v1.NotificationTemplate
	0,  // 7: notification.v1.UpdateTemplateRequest.template:type_name -> notification.v1.NotificationTemplate
	1,  // 8: notification.v1.ListTemplateVersionsResponse.versions:type_name -> notification.v1.NotificationTemplateVersion
	1,  // 9: notification.v1.CreateTemplateVersionRequest.version:type_name -> notification.v1.NotificationTemplateVersion
	3,  // 10: notification.v1.NotificationService.ListTemplates:input_type -> notification.v1.ListTemplatesRequest
	5,  // 11: notification.v1.NotificationService.GetTemplate:input_type -> notification.v1.GetTemplateRequest
	6,  // 12: notification.v1.NotificationService.CreateTemplate:input_type -> notification.v1.CreateTemplateRequest
	7,  // 13: notification.v1.NotificationService.UpdateTemplate:input_type -> notification.v1.UpdateTemplateRequest
	8,  // 14: notification.v1.NotificationService.DeleteTemplate:input_type -> notification.v1.DeleteTemplateRequest
	9,  // 15: notification.v1.NotificationService.ListTemplateVersions:input_type -> notification.v1.ListTemplateVersionsRequest
	11, // 16: notification.v1.NotificationService.CreateTemplateVersion:input_type -> notification.v1.CreateTemplateVersionRequest
	12, // 17: notification.v1.NotificationService.ApproveTemplateVersion:input_type -> notification.v1.ApproveTemplateVersionRequest
	4,  // 18: notification.v1.NotificationService.ListTemplates:output_type -> notification.v1.ListTemplatesResponse
	0,  // 19: notification.v1.NotificationService.GetTemplate:output_type -> notification.v1.NotificationTemplate
	0,  // 20: notification.v1.NotificationService.CreateTemplate:output_type -> notification.v1.NotificationTemplate
	0,  // 21: notification.v1.NotificationService.UpdateTemplate:output_type -> notification.v1.NotificationTemplate
	2,  // 22: notification.v1.NotificationService.DeleteTemplate:output_type -> notification.v1.DeleteResponse
	10, // 23: notification.v1.NotificationService.ListTemplateVersions:output_type -> notification.v1.ListTemplateVersionsResponse
	1,  // 24: notification.v1.NotificationService.CreateTemplateVersion:output_type -> notification.v1.NotificationTemplateVersion
	1,  // 25: notification.v1.NotificationService.ApproveTemplateVersion:output_type -> notification.v1.NotificationTemplateVersion
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
